### ISSUE TITLE
Missing AT in SEPA List

### ISSUE THREAD

**Issue by wpichler** [OCA/bank-payment#1002]
Austria with IBAN Code AT is missing in the support sepa codes list

https://github.com/OCA/bank-payment/blob/baf733b356f7154410dd09f48933e02efc0c0dc2/account_banking_pain_base/models/account_payment_order.py#L65

Take a look at https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2020-10/EPC409-09%20EPC%20List%20of%20SEPA%20Scheme%20Countries%20v3.0_1.pdf

**Comment by mtbochaca** [comment]
I added a pull request with Austria (AT) and Andorra (AD)

https://github.com/OCA/bank-payment/pull/1025
