### ISSUE TITLE
Use of Waiting accounts in payment orders (Cash discount)

### ISSUE THREAD

**Issue by chrisdec** [OCA/bank-payment#101]
Hello,

I have a question regarding the process of the payment order. Normally, it’s recommended to use waiting accounts to avoid paying two times the same invoice. However, I have some customers who work with cash discount.

Let’s take an exemple :

I have an invoice of 121 € with due date of 31/01/2015 but if I pay before 15/01/2015, I only pay 119€.

If they use waiting accounts, the amount on the waiting account will be the amount they paid in the payment order. The reconciliation will be partial as the paid amount is not the total amount of the invoice and the invoice will stay open. Moreover, as the invoice is still open, Odoo will propose to pay it a second time.  

If they don’t use the waiting accounts, they can reconcile easily on the bank statement with the cash discount account but here also, Odoo will propose to pay the invoice a second time before the first bank statement and the reconciliation.

What do you suggest?

Thanks in advance for the answer,

Christelle

**Comment by sbidoul** [comment]
This relates to #93. Indeed, moves to the transfer account create partial reconciles, and https://github.com/acsone/bank-payment/pull/5 works best when invoices are fully reconciled as soon as possible.

A solution could be to do the write-off of the difference at the same time as the move to the transfer account.

What do others think?

**Comment by adrienpeiffer** [comment]
I agree with your proposition @sbidoul.

**Comment by sbidoul** [comment]
The problem is that we would end-up re-creating a full reconcile/writeoff wizard that already exists.

So maybe adding a button on the payment order to show the unreconciled transfer journal entries would be enough? From there, the user could easily finalise the write-off using the standard wizard.

**Comment by sbidoul** [comment]
https://github.com/acsone/bank-payment/commit/f6c8cd782caea6c3a49bc349128b240ab1618590 in https://github.com/acsone/bank-payment/pull/5 provides a solution for this, letting the user easily register cash discount differences just after doing the payment order:
- a button on the payment order to access the partially reconciled payments moves
- from that screen, the user can use the standard reconcile with writeoff feature to do the writeoff to the cash discount account, therefore completely reconciling the invoices which in turn will not be proposed anymore in payment orders

**Comment by pedrobaeza** [comment]
This is already solved.
