### ISSUE TITLE
[15] [BUG] Format of printed mandates lost

### ISSUE THREAD

**Issue by jabelchi** [OCA/bank-payment#1026]
Format of printed mandates lost. Lines do not appear. Invalid text sizes.

## Module
account_banking_sepa_direct_debit

## Describe the bug
Format of printed mandate not correct.

## To Reproduce
**V15** 

1. Menú: Invoicing / Customers / Banking mandates
2. Click on one mandate of the view
3. Click on Print

Please find the attached files. V14 is OK, But V15 is wrong.
[V15 - Sepa Mandate.pdf](https://github.com/OCA/bank-payment/files/10566816/V15.-.Sepa.Mandate.pdf)
[V14 - Sepa Mandate.pdf](https://github.com/OCA/bank-payment/files/10566817/V14.-.Sepa.Mandate.pdf)

**Comment by pedrobaeza** [comment]
Are you going to provide a patch for this?

**Comment by jabelchi** [comment]
No. I'm sorry. I'm a functional and I don't have the skills.

**Comment by pedrobaeza** [comment]
And no technical stuff in your company to do the contribution?

**Comment by martiqubiq** [comment]
@jabelchi The report it's OK in V15! You have to put the parameter 'report.url' in system parameters.

**Comment by pedrobaeza** [comment]
It was fixed by us on https://github.com/OCA/bank-payment/pull/1066
