### ISSUE TITLE
[14.0] [BUG] Payment line amount wrongly reconciled in grouped payment

### ISSUE THREAD

**Issue by dannyadair** [OCA/bank-payment#1030]
## Module
account_payment_order

## Describe the bug
When grouping transactions in a payment order so that one payment is made for multiple lines:

If the amount of a payment line is manually reduced, the all-in-one reconciliation in `generated2uploaded()` will apply the underpayment ("leftover") to the last payment line(s), not the one(s) specified.

## To Reproduce
**Affected versions**: 14.0 (presumbably others)

1. Configure a payment mode with "Group Transactions in Payment Orders"
2. Add a few invoices from the same supplier to a payment order using that payment mode
3. Change the amount of the first (or second) line so that it's underpaid, let's say by $100
4. Confirm payments, create payment file, mark as uploaded
5. The underpayment is applied to the last invoice instead of the one specified

**Expected behavior**
Each invoice to be reconciled against their specified amount.

**Additional context**
Please note we have limited knowledge in this area.
We only use `account_payment_order` for paying supplier invoices and the following code only solves our immediate issue of short-paying a supplier invoice. Debit orders - and credit notes in payment orders - are not handled by the following code.

From https://github.com/OCA/bank-payment/blob/14.0/account_payment_order/models/account_payment_order.py#L409

```
    def generated2uploaded(self):
        self.payment_ids.action_post()
        # Perform the reconciliation of payments and source journal items
        for payment in self.payment_ids:
            (
                payment.payment_line_ids.move_line_id
                + payment.move_id.line_ids.filtered(
                    lambda x: x.account_id == payment.destination_account_id
                )
            ).reconcile()
        self.write(
            {"state": "uploaded", "date_uploaded": fields.Date.context_today(self)}
        )
        return True
```

In our proposed change, we do partial reconciliation of all non-matching amounts first:
```
    def generated2uploaded(self):
        """Post payments and reconcile against source journal items
        Partially reconcile payments that don't match their source journal items,
        then reconcile the rest in one go.
        """
        self.payment_ids.action_post()
        # Perform the reconciliation of payments and source journal items
        for payment in self.payment_ids:
            payment_move_line_id = payment.move_id.line_ids.filtered(
                lambda x: x.account_id == payment.destination_account_id
            )
            apr = self.env["account.partial.reconcile"]
            excl_pay_lines = self.env["account.payment.line"]
            for line in payment.payment_line_ids:
                if line.amount_currency != -line.move_line_id.amount_residual_currency:
                    apr.create(
                        {
                            "debit_move_id": payment_move_line_id.id,
                            "credit_move_id": line.move_line_id.id,
                            "amount": line.amount_company_currency,
                            "debit_amount_currency": line.amount_currency,
                            "credit_amount_currency": line.amount_currency,
                        }
                    )
                    excl_pay_lines |= line
            pay_lines = payment.payment_line_ids - excl_pay_lines
            if pay_lines:
                (pay_lines.move_line_id + payment_move_line_id).reconcile()
        self.write(
            {"state": "uploaded", "date_uploaded": fields.Date.context_today(self)}
        )
        return True
```

**Comment by dannyadair** [comment]
P.S.: The above was before the merge of PR1015 https://github.com/OCA/bank-payment/commit/596b51918f65fe2f4f6fa47e85aeacfa57b10d85 - investigating repercussions

**Comment by dannyadair** [comment]
Sorry the grouping here is just the simple grouping of the lines to single payments.
The latest version works for us with the above code adjustment.
(without new grouped output addon installed)

**Comment by pedrobaeza** [comment]
I see the problem you commented. Can you propose the patch adding a test case of this one?

**Comment by dannyadair** [comment]
[DRAFT] https://github.com/OCA/bank-payment/pull/1049
tests coming

**Comment by dannyadair** [comment]
@pedrobaeza Added test to #1049 for handling of manually adjusted invoice payment

**Comment by pausanchezqubiq** [comment]
Hey @dannyadair, I think this issue should be closed since the PR https://github.com/OCA/bank-payment/pull/1049 is merged

**Comment by pedrobaeza** [comment]
Yes, but the patch should be forward ported.

**Comment by dannyadair** [comment]
This issue was for 14.0 - I will forwardport the patch to 15 and 16
