### ISSUE TITLE
8.0 data migration needed for databases with account_banking_payment in 7.0

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/bank-payment#105]
While the functionality of account_banking_payment has been ported and modernized by @sbidoul in #65, some migration is still needed for users of account_banking_payment in 7.0. At least the workflow activities need their XML id ported to the next module, for instance https://github.com/OCA/bank-payment/pull/65/files#diff-b741f84bba31476d9c79670c503c8f66R12

**Comment by pedrobaeza** [comment]
It seems to be already covered, so I close.
