### ISSUE TITLE
[14.0][account_payment_sale]

### ISSUE THREAD

**Issue by matteoopenf** [OCA/bank-payment#1059]
## Module
account_payment_sale

## Describe the bug
print report sale_order 

## To Reproduce
**Affected versions**:

- [ ] 14.0

1. Create order
2. print report order 
3. errore File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'sale.order' object has no attribute 'payment_mode_id'
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 327, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_report_saleorder_document_648
  File "<template>", line 1, in body_call_content_646
AttributeError: 'sale.order' object has no attribute 'payment_mode_id'

Error to render compiling AST
AttributeError: 'sale.order' object has no attribute 'payment_mode_id'
Template: sale.report_saleorder_document
Path: /t/t/div/p[3]
Node: <p t-if="doc.payment_mode_id.note" id="payment_mode_note">
                <strong>Modo di Pagamento:</strong>
                <span t-field="doc.payment_mode_id.note"/>
            </p>

**Expected behavior**

print order correctly

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
@alexis-via  I see the problem is only the pre-commit https://github.com/OCA/bank-payment/pull/820 is it right?

**Comment by chusamo** [comment]
I think this issue should be closed since the PR #820 is merged

**Comment by matteoopenf** [comment]
> I think this issue should be closed since the PR #820 is merged

confirm
