### ISSUE TITLE
[16.0] account_payment_mode: Note field box too narrow

### ISSUE THREAD

**Issue by ao-landoo** [OCA/bank-payment#1085]
We've seen account.payment.mode form view's note field is too narrow, it should be much wider.

![descarga](https://github.com/OCA/bank-payment/assets/74420754/605bf9e4-dd5a-4c25-94c8-5d5d06629250)

@ThomasBinsfeld

**Comment by pausanchezqubiq** [comment]
Hey @ao-landoo, I have made a PR with the fix: https://github.com/OCA/bank-payment/pull/1088

**Comment by pausanchezqubiq** [comment]
Hey @ao-landoo, I closed the pr by mistake, it's here: https://github.com/OCA/bank-payment/pull/1092
