### ISSUE TITLE
[16.0] account_payment_partner: partner_bank_id empty for out_invoice with l10n_ch

### ISSUE THREAD

**Issue by grindtildeath** [OCA/bank-payment#1091]
## Module
account_payment_partner

## Describe the bug
With the swiss localization, field account.move.partner_bank_id is used to generate QR reference and QR code for customer invoices: https://github.com/odoo/odoo/blob/16.0/addons/l10n_ch/models/account_invoice.py#L40-L44
This field is computed in standard to the company's partner bank account (again for customer invoices): https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_move.py#L778-L783
Now, with the module account_payment_partner installed, the computation of this field is redefined to set a `False` value in case the move is not a vendor bill: https://github.com/OCA/bank-payment/blob/16.0/account_payment_partner/models/account_move.py#L89-L99

Looking at this piece of code, the assumption "No bank account assignation is done for out_invoice as this is only needed for printing purposes" is wrong in the context of swiss localization. I'm curious though to know how this "can conflict with SEPA direct debit payments" and if that's still the case since the original message was about avoiding to assign a value from the payment mode and not to remove a value computed by the super function: https://github.com/OCA/bank-payment/commit/fbb15b4d587cd3461c91ebbc62bf5b2870513dd5#diff-e896d047b041c58135104731ffd6608aa8f8cd47b83ca6f4822051b8be32818eL36-R39

FTR, this bug only appears in v16.0 because in previous versions, the field partner_bank_id was passed explicitly when creating a invoice from a sale order: https://github.com/odoo/odoo/blob/15.0/addons/sale/models/sale_order.py#L633

## To Reproduce
**Affected versions**: 16.0

1. Install l10n_ch and account_payment_partner
2. Define a bank account on the company partner
3. Create a customer invoice

**Expected behavior**
The customer invoice should use the bank account defined on the company partner to be able to be valid with swiss QR requirements.

**Additional context**

**Comment by grindtildeath** [comment]
@carlosdauden @pedrobaeza @alexis-via 
Your help would be appreciated here, as I'm not sure what's the "good" solution to this.

Should we remove the override of the compute function as the conflict with SEPA might not exist anymore?

Could we define other conditions to avoid overwriting the value computed by Odoo in the super function?

**Comment by yvaucher** [comment]
Had a look with @grindtildeath to me as the partner_bank_id is now a computed field we should not empty it but instead override the compute method. In this override we then compute the bank account based on the payment mode for instance if the bank account is fixed, use the specified bank account.

For the Direct Debit comment, if it makes still sense, this should be handled by the module account_payment_sepa_direct_debit.
