### ISSUE TITLE
V16 account_banking_sepa_direct_debit

### ISSUE THREAD

**Issue by cesarsc79** [OCA/bank-payment#1131]
## Module
account_banking_sepa_direct_debit

## Describe the bug

When the SEPA file is generated, the debtor's IBAN is filled in with the creditor's IBAN.
Debtors' IBANs do not appear in the XML file

## To Reproduce
V16:

generate a SEPA DEBITOR xml file

**Expected behavior**
 the debtor's IBAN is filled in with the debtor's  IBAN

**Comment by 10537** [comment]
I confirm that, we have the same error. @rvalyi @ovnicraft @azmeuk

**Comment by 10537** [comment]
Hi @cesarsc79 

You can used this [PULL-1136](https://github.com/OCA/bank-payment/pull/1136) for resolve your problem until this will be merge to the branch 16.0

best regards,

**Comment by cesarsc79** [comment]
> Hi @cesarsc79
> 
> You can used this [PULL-1136](https://github.com/OCA/bank-payment/pull/1136) for resolve your problem until this will be merge to the branch 16.0
> 
> best regards,

Thanks
