### ISSUE TITLE
Account move dates are always set to payment date in account_payment_order

### ISSUE THREAD

**Issue by giarve** [OCA/bank-payment#1175]
## Module
account_payment_order

## Describe the bug
We are not accounting the moves when they are created by the accounting user but when the bank would process the payments, making outstanding payments account useless if the bank processes the scheduled payments within the same day as they are scheduled by the payment order!

Important not to confuse payment date (when the payment line is scheduled) with move accounting date (when the moves are written to the journal).

## To Reproduce
**Affected versions**: tested on 14.0, but it probably happens on newer versions

1. set `date_prefered` to any selection different than `now`
2. check account.move account dates, they are set to payment line date (for instance, the bank will have this date on the SEPA file).
3. confirm file upload (`generated2uploaded` function)
4. if we go to the balance sheet, we see that we have no outstanding payments/receipts because they are not accounted for, yet! We would have to set the period/range of the balance sheet to the future when the bank processes the payments.

**Expected behavior**
By default, I expect the accounting date to be the same day the payment order has the file *uploaded to the bank*, as the payment is now scheduled to payment line date, but the bank is now responsible for it.

**Additional context**
I am assuming that the outstanding payments are related to the time period since the user uploads the file to the bank (even if the scheduled payments are set in the future), up to the point where the user imports the account statements (then they are moved to the suspense account).
If outstanding payments start when the bank is processing the payments (scheduled payment date), as scheduled from the user, this issue can be closed without no further action.

**Comment by pedrobaeza** [comment]
This was changed in #1038

**Comment by giarve** [comment]
> This was changed in #1038

Yes, I commented there, but it is actually a separate thing. Sorry I messed up and should have created a new issue. I do agree with the change made in that PR. But this is different.

In this case, I want to set the accounting date always to Today for the generated account moves, as they are currently set to payment date (otherwise outstanding balances in the accounts are usually set and gone on the same day).

**Comment by pedrobaeza** [comment]
I don't agree with such change. If you want this, just set the date manually with the feature referenced before, or develop a custom extension doing that.

**Comment by giarve** [comment]
> I don't agree with such change. If you want this, just set the date manually with the feature referenced before, or develop a custom extension doing that.

The problem with current behavior is that the outstanding payment accounts are only tracking the balances at the moment the bank starts processing the payment (scheduled payment) until the bank statement is imported (this is correct in both scenarios), but not when the accounting user confirms the scheduled payment (uploads the file).

Is there any reasoning behind not changing it? Is this the expected flow for the outstanding accounts?

The feature referenced before would not help with this as it would change the payment scheduled dates but we would not want to change the payment scheduled dates here, only the account move dates (and it would apply to all payment orders, by default).

**Comment by giarve** [comment]
I will leave the issue open until tomorrow (working day) and will close it after, if nobody else replies.

If someone needs a quick hack, it should be as easy as:

```
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

from odoo import _, api, fields, models


class AccountPaymentOrder(models.Model):
    _inherit = "account.payment.order"

    def generated2uploaded(self):
        today = fields.Date.context_today(self)

        for payment_move in self.payment_ids.move_id:
            payment_move.date = today
            payment_move.line_ids.date = today

        return super().generated2uploaded()
```

but please drop a message if interested to create an extension module with tests.
