### ISSUE TITLE
[15.0] account_payment_mode - error in multicompany

### ISSUE THREAD

**Issue by iTecan** [OCA/bank-payment#1179]
## Module
The name of the module that has a bug.
**account_payment_mode**

## Describe the bug
If we have the STRIPE payment provider configured and in use, when generating a new company, and when applying the Chart of Accounts from Settings->Invoicing->Fiscal Location, it gives error.
When giving error it does not finish to install the Accounting Plan, neither the taxes, diaries, etc.

## To Reproduce
**Affected versions**: Odoo CE 15 (I think that in the previous ones too, but I have not checked it.)

1. Enabled Accquirer Payment STRIPE
2. Create a new company
3. Apply the Accounting Plan from Settings.

**Expected behavior**
It should not generate error and finish installing the fiscal localization.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
OS:  Ubuntu 20.04
Python: 3.8

------------------------------------
Possible solution:
Error in account_journal.py -> methods: _default_inbound_payment_methods and _default_outbound_payment_methods.

![image](https://github.com/OCA/bank-payment/assets/62338632/c165f417-c78c-40ee-95f3-0e146cfa2d4f)

These functions recreate all the generated payment modes, throwing an error in the constraints.
If you leave the Odoo code base in these functions the process finishes correctly.

![image](https://github.com/OCA/bank-payment/assets/62338632/da08adf3-98bf-4327-92bc-f13450f13835)

**Comment by pedrobaeza** [comment]
Are you using latest code version? Please put the stack trace of the error.
