### ISSUE TITLE
[16.0] payment order communication does not use structured communication payment reference

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#1195]
## Module

account_payment_order

## Describe the bug

I am creating customer invoices with a structured communication which lands in the `payment_reference` field.
When I add such an invoice to a debit order, the `ref` field is used as communication, and the payment reference field is ignored.

This relates to this code section 

https://github.com/OCA/bank-payment/blob/55718af9a49b00598d06db2d6a045deb9cddd530/account_payment_order/models/account_move.py#L50-L60

and in particular line 54 and 55, which gives priority to the `ref` field over the payment reference for invoices where the `reference_type` is `structured`.

Does anyone known why it is done like this?

@pedrobaeza @alexis-via @luc-demeyer

**Comment by pedrobaeza** [comment]
This was extracted in this method according what it was, so no real intention if this has been switched. We are not working with `structured` communication type. Feel free to make a PR amending that while the rest is not changed.

**Comment by luc-demeyer** [comment]
No idea why the code is that way, we should fix it.
Please make a PR.

**Comment by sbidoul** [comment]
Ok thanks. I will then do a PR that removes lines 54 and 55.

And then I will dig into how to use structured payment references for purchase invoices...

**Comment by luc-demeyer** [comment]
@sbidoul 
supplier invoces, cf. https://github.com/Noviat/noviat-apps/tree/16.0/l10n_be_invoice_bba_supplier
we can move this module ito l10n-belgium.
