### ISSUE TITLE
WIP: Migrate module account_banking_partner_journal_account

### ISSUE THREAD

**Issue by ploegvde** [OCA/bank-payment#121]
Hello,
We want to migrate module: account_banking_partner_journal_account. This is now in repo "bank-payment". We will remove the dependency of the old account_banking modules and integrate it with the new v8 reconciliation. I don't think the module should stay here, but better to move to "bank-statement-reconcile".

So wip. Please let me know where the module should be put?

**Comment by pedrobaeza** [comment]
Hi, Erwin, you are right that this module should be in bank-statement-reconcile. Please make the corresponding PRs to remove from `**unported** here, and to be included in the other repo.

Thanks.

**Comment by pedrobaeza** [comment]
Closing as the PR is done.
