### ISSUE TITLE
[8.0] SEPA credit transfer XML structure

### ISSUE THREAD

**Issue by jordillinares** [OCA/bank-payment#124]
Hi!

A customer of mine is complaining that a bank they work with accepts their credit transfer XML file, but the bank office that must accomplish with the payment says they are not able to make payments, because the issuer identifier is missing.

Despite my lack of knowledge about SEPA, I've spent quite a few hours trying to figure out what could be the problem. And maybe it's just my ignorance, but I've found something weird to me.

I'll go straight to the point:

Why, in account_banking_pain_base/banking_export_pain.py, the code for 2.125 is

``` python
            creditor_ref_info_type_issuer_2_125.text = \
                line.struct_communication_type
```

I've read that 2.125 represents the identifier of the reference issuer, so I find weird that in my customer's transfer files its generated value is always 'ISO', instead of their vat id.

Wouldn't it have to be something like

``` python
            creditor_ref_info_type_issuer_2_125.text = \
                line.order_id.company_id.initiating_party_issuer
```

What do you SEPA experts think?

**Comment by pedrobaeza** [comment]
Hi, Jordi, we are debating something similar to this here: https://github.com/OCA/bank-payment/pull/112#issuecomment-73986572, and this is information is relevant for resolving that PR and decides about this one.

**Comment by pedrobaeza** [comment]
Solved already
