### ISSUE TITLE
Python library not installed: unidecode

### ISSUE THREAD

**Issue by apropsi** [OCA/bank-payment#1242]
I try to install in a Odoo 16 windows.

But message "Python library not installed: unidecode"

I try to pip install Unidecode -> Did
But still the error.

Any clue?

Thanks in advance

**Comment by pedrobaeza** [comment]
Sorry, this is not an error of the module itself, but how you are trying to deploy and prepare pre-requisites. Go to Odoo forums to get some help on that matter.
