### ISSUE TITLE
WIP: Migrate module account_bank_statement_tax

### ISSUE THREAD

**Issue by ploegvde** [OCA/bank-payment#126]
Hello,

Just an issue to infom tha we il migrate ths module  v8.

**Comment by sbidoul** [comment]
I'm not very familiar with this module, but is that not a standard feature in 8.0?

**Comment by ploegvde** [comment]
Shit, you are right. Missed that. You can indeed add tax to a statement line in V8. Case closed.

**Comment by pedrobaeza** [comment]
According this, I have made a PR to remove it from 8.0 branch: https://github.com/OCA/bank-payment/pull/128
