### ISSUE TITLE
Account Payment Order ERROR 

### ISSUE THREAD

**Issue by AR-Mate** [OCA/bank-payment#1271]
Hi,

I have Odoo 16 Enterprise. When I activate the Account Payment Order module, it is successful, but the Payment Order window does not appear in  Invoicing/Accounting > Vendors > Payment Order and Invoicing/Accounting > Customers > Debit Orders. 
Additionally, I do not see any installation errors or anything; it's just that the window that should be generated does not appear.

I hope for your response.

**Comment by vdewulf** [comment]
Hello,
Could you provide information about the version?
Do you manage to reproduce the bug on OCA Runboat (on Odoo Community Edition)? It'll help see where is the issue's origin.
Did you check the user rights as well?
Thanks
