### ISSUE TITLE
[16.0] account_payment_mode incompatible with payment_stripe and payment_adyen

### ISSUE THREAD

**Issue by EmilioPascual** [OCA/bank-payment#1283]
## Module
account_payment_mode

## Describe the bug
If you has installed module `account_payment_mode` and any of this modules `payment_stripe` or `payment_adyen`, when you install a localisation module such as `l10n_generic_coa` the following error happens
```
odoo.tools.convert.ParseError: while parsing /opt/odoo/auto/addons/l10n_generic_coa/data/l10n_generic_coa_post.xml:79
Some payment methods supposed to be unique already exists somewhere else.
([adyen] Adyen (inbound), [stripe] Stripe (inbound))
View error context:
'-no context-'
```

## To Reproduce
**Affected versions**:

1. In a new db.
2. Install `account_payment_mode`
3. Install `payment_stripe` or `payment_adyen`
4. Try install `l10n_generic_coa`

**Expected behavior**
Having a database with modules installed in that order

**Additional context**
Issue closed: https://github.com/OCA/bank-payment/issues/977
PR https://github.com/OCA/bank-payment/pull/1093 with fix but it didn't solve it

@moduon MT-6161

**Comment by yajo** [comment]
Maybe the fix is to backport https://github.com/OCA/bank-payment/pull/1312?

**Comment by EmilioPascual** [comment]
Yes, I did the backport in https://github.com/OCA/bank-payment/pull/1329 a months ago and I forgot close the issue.
