### ISSUE TITLE
SEPA Direct Debit 008.003.02 (Germany)

### ISSUE THREAD

**Issue by jay-emipro** [OCA/bank-payment#129]
SEPA Direct Debit Transfer should allow to export file in pain version 008.003.02 being used in Germany.  In Sepa Direct Debit Transfer, this pain version is not supported. 

Thanks in advance.

**Comment by alexis-via** [comment]
We see some references to it on the Web, but it doesn't seem to be listed on the official iso20022 website, see http://www.iso20022.org/full_catalogue.page

**Comment by pedrobaeza** [comment]
As there hasn't been any answer, I close.

**Comment by alexis-via** [comment]
There is the same kind of discussion in Tryton: https://bugs.tryton.org/issue4216

**Comment by tremlin** [comment]
There seems to be some kind of documentation at https://www.corporates.commerzbank.com/portal/media/corporatebanking/hauptportal/agb-13/archiv-der-vertragsbedingungen/2013-1/datenformate_sepa_kunde_bank_v2-7_en.pdf

**Comment by alexis-via** [comment]
MS ERP have a special patch for the special versions of PAIN for Germany:
https://support.microsoft.com/en-us/kb/2880634

**Comment by alexis-via** [comment]
Here are all the differences between pain.001.001.03 (EPC version) and pain.001.003.03 (for Germany):

https://www.hypovereinsbank.de/content/dam/hypovereinsbank/cib/pdf/ebanking/ebanking-uebersicht/SEPA_DE_Vgl_CGI_EPC_DK_E.pdf

For the use-case of the OCA module... it is exactly the same ! So I plan to add support for pain.001.003.03 in v9.

In this document, if I understand it correctly, the Germany-specific stuff is a sort of "subset" of the version of the EPC.

**Comment by alexis-via** [comment]
In fact, pain.001.003.03 is already supported by account_banking_sepa_credit_transfer (I was not aware of that !) ; we only miss the german-specific version for direct debit.

**Comment by alexis-via** [comment]
I confirm that I added support for pain.001.003.03 and 008.003.02 in bank-payment v9. It will be published soon.
