### ISSUE TITLE
[RFC] support `allow_out_payment`

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#1330]
In 16 (not checked other versions yet), res.partner.bank has an `allow_out_payment` that can be used to check if payments are allowed to that bank account.

This is useful to implement a process to control bank accounts before using them.

We may want to support this field in account_payment_order, to refuse validating outgoing payment orders to bank accounts where this field is False.

**Comment by pedrobaeza** [comment]
It should be controlled even before, excluding that bank accounts in the selections.

cc @carolinafernandez-tecnativa

**Comment by sbidoul** [comment]
> It should be controlled even before, excluding that bank accounts in the selections.

Maybe. It might still be useful to prepare the invoices and payment order while the bank account validation process goes on.

**Comment by pedrobaeza** [comment]
You are thinking in the check as a temporary one to be marked "when finished", but the check is there not specifically for that, but according the nomenclature, I think its usage is for marking accounts that shouldn't be used on that operations never. How is this used in enterprise?

**Comment by sbidoul** [comment]
17.0 CE is more explicit about the intended use of the field

![image](https://github.com/user-attachments/assets/330ffce4-f600-4efa-9309-84e387c3b23e)

**Comment by sbidoul** [comment]
And in enterprise, the check is done at the validation of the payment batch.

**Comment by pedrobaeza** [comment]
#1177 in process of merging.
