### ISSUE TITLE
[17.0] ParseError: while parsing /home/odoo/src/user/account_payment_order/views/account_payment_views.xml:22: Field `xml_str` does not exist

### ISSUE THREAD

**Issue by admchristian** [OCA/bank-payment#1366]
## Module
account_payment_order

## Describe the bug
On upgrade to 17.0, the module emits this error:

```
odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/account_payment_order/views/account_payment_views.xml:22
Fehler bei der Validierung der Ansicht nahe:

<form string="Register Payment">
                    <header>
                        <button name="action_post" string="Confirm" type="object" class="oe_highlight" invisible="state != 'draft'" data-hotkey="q"/>

Field `xml_str` does not exist

View error context:
{'file': '/home/odoo/src/user/account_payment_order/views/account_payment_views.xml',
 'line': 1,
 'name': 'account.payment.form',
 'view': ir.ui.view(4573,),
 'view.model': 'account.payment',
 'view.parent': ir.ui.view(561,),
 'xmlid': 'view_account_payment_form'}
```

## To Reproduce
**Affected versions**: 17.0

1. Upgrade to V17

**Expected behavior**
Its expected to upgrade fine.

**Additional context**

I have seen that this is the offending part:

```
https://github.com/OCA/bank-payment/blob/17.0/account_payment_order/views/account_payment_views.xml#L22-L31```
```

Where this is the inherited parent:

```
https://github.com/odoo/odoo/blob/17.0/addons/account/views/account_payment_view.xml#L149-L345
```

But as I am only on my way into Odoo, I cannot make any sense of the error just yet. The "<field name="arch" type="xml">" look fine to me.

Any help is appreciated.

**Comment by pedrobaeza** [comment]
I don't get it. First you install v16 and then v17?

**Comment by admchristian** [comment]
> I don't get it. First you install v16 and then v17?

No, this error happens on upgrade. The V16 is already there.

**Comment by pedrobaeza** [comment]
You can't upgrade without enterprise or OpenUpgrade, and this last one is not yet ready for v17. The problem is not with the module, but that you are trying to do something incorrect.

**Comment by admchristian** [comment]
But this is on odoo.sh with subscription, and the enterprise upgrade service. However the database step is done, the instance runs. Just the module upgrade does not. Could you point me in the right direction?

If in the README of this repo there is mentioned

> OCA, or the [Odoo Community Association](http://odoo-community.org/), is a nonprofit organization whose mission is to support the collaborative development of Odoo features and promote its widespread use.
>the collaborative development of Odoo features and promote its widespread use.

This is a strange way of conduct.

**Comment by pedrobaeza** [comment]
Look for any view containing a field `xml_str` and remove it, as that's not part of this module.
