### ISSUE TITLE
bug for account_payment_partner

### ISSUE THREAD

**Issue by fardinmardani** [OCA/bank-payment#1389]
## Module
account_payment_partner

## Describe the bug
XPath of this module in file report_invoice.xml have error
![image](https://github.com/user-attachments/assets/08c06dc5-a4de-4bf7-8908-3fd718ca3aac)

and in main module I have this path
![image](https://github.com/user-attachments/assets/ec42e859-3637-4193-9db6-2439f51d2b3b)

**Comment by pedrobaeza** [comment]
This is because your DB seems modified somehow (other module or manual changes) that provokes this error, but it's not fault of the module itself, so closing.

**Comment by fardinmardani** [comment]
I replace the xpath with 
![image](https://github.com/user-attachments/assets/76a12035-819b-4bc3-abbc-f53447ae12fd)
and fixed
