### ISSUE TITLE
Wrong Payment Date by creating a Payment Order

### ISSUE THREAD

**Issue by HiJohan** [OCA/bank-payment#147]
When creating a Payment Order, the duedate will be used as payment date. 
That is wrong. The payment date is the right date to pay the invoices.

When export the xml file by using the SEPA Credit Transfer Files, i got the due data as payment data.
When the duedate is in the past, i can not pay this invoice.

Please make the adjustement to use only the payment date in the payment order.

Thanks in advance.

**Comment by pedrobaeza** [comment]
You can choose which date to use in the header of the payment order (due date, inmediate and fixed date). Select one of the other two.

**Comment by HiJohan** [comment]
Thanks Pedro,

I already select the immediate and fixed. They are working Ok.

But selecting on due date, you can not give an other payment date.
For example I select the invoices with due date until this Friday, but will pay them the beginning of next week. I can't adjust the payment date to the beginning of next week.

I think you always need to have the possibility to adjust the payment date if when using this due date option.?

**Comment by pedrobaeza** [comment]
No, I don't think so. You already have the option to put a fixed date. If you need another dates, change the due date on the source move line.
