### ISSUE TITLE
8.0 SEPA Credit Transfer: Combine payments in payment order

### ISSUE THREAD

**Issue by HiJohan** [OCA/bank-payment#152]
When making a payment order, I miss the possibility to combine payments. 
For example:  I so have 20 open invoice to pay to a vendor. I will prepare a payment for only the total amount. And send a detailed payment report with the 20 invoice a will pay.

Also to combine Credit Notes and combine the open invoices of a Vendor who is also a customer.

Do somebody knows how to solve this or do have a work around?

Thanks in advance.

Johan Bosma

**Comment by pedrobaeza** [comment]
This is available (auto-grouping of the lines of the same partner) in the last version, so I close.
