### ISSUE TITLE
Why don't we populate the date_to_pay if it is today?

### ISSUE THREAD

**Issue by matthieuchoplin** [OCA/bank-payment#155]
In the module account_banking_payment_export/wizard/payment_order_create.py, the method _prepare_payment_line is not going to populate the date of the payment_line if the 'Due date' (date_maturity) of the account_move_line is today.
Is it normal? Don't we want to have the date on the payment line if i is today?

**Comment by pedrobaeza** [comment]
This is done after when confirming the payment order.
