### ISSUE TITLE
many transactions not regonized

### ISSUE THREAD

**Issue by temmink** [OCA/bank-payment#16]
After importing a dutch bank statements file from the ING, I got the following screen:

![import_log](https://cloud.githubusercontent.com/assets/890128/3571378/ca510fa0-0b5c-11e4-9d32-3ee373c491e4.png)

Many transactions are not processed because of not recognizing the correct bankaccount number. 

The system is complaining about "Statements found for unknown account 68xxx" and "Statements found for account 06xxxxxx, but no default journal was defined.

This is a little strange, because I have setup "Default Import Settings for Bank Accounts"
in the settings of the accounting section.

I also put a default journal in there.

My information entered there is the IBAN number of my account, together with the national account (with leading zero). I also tried without the leading zero in the national account, but this doesn't make any difference at all.

Why is openerp mixing up the number of the bankaccount. (with/without zero) and not matching the national number.

**Comment by temmink** [comment]
Is it allowed to have multiple "default import settings for Bank Accounts"?
Because then i can solve the problem with national bankaccount and Iban  account.

or is this not allowed?

**Comment by StefanRijnhart** [comment]
Which format are you importing?

**Comment by temmink** [comment]
ing MT940 format, sorry for not mentioning it.

**Comment by StefanRijnhart** [comment]
Confirmed. We used to have this crappy webservice for IBAN and normalized the domestic account numbers along the way with leading zeroes. This webservice is now deprecated as it gave incorrect results, but it seems normalization is now inconsistent during import and account number lookup.

**Comment by temmink** [comment]
okay, so i have to setup multiple default import settings for Bank Accounts, to bypass this problem?

**Comment by StefanRijnhart** [comment]
No, I think we should adapt the search function to abstract from leading zeroes.

**Comment by temmink** [comment]
I agree, that's a much better solution. 
Unfortunately I'm not that great with python to do it myself.
So I was hoping that the workaround would be possible for the time being.

**Comment by StefanRijnhart** [comment]
Can you try https://github.com/OCA/banking/pull/18?

**Comment by temmink** [comment]
I have merged #18 and restarted the server.
Now importing 5 statements with 46 transactions.

all succesfull!
![import_log](https://cloud.githubusercontent.com/assets/890128/3584871/796f7446-0c1f-11e4-946d-8ee43361a263.png)

:+1:

**Comment by StefanRijnhart** [comment]
Thanks for testing!
