### ISSUE TITLE
8.0 account_direct_debit: cannot use button "Debit Denied" on invoice

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#162]
I'm trying to understand how the "storno" field on payment.line defined in the module account_direct_debit works.

Here is my code analysis for the module account_direct_debit for v8:
in views/account_invoice.xml we have:

```
<button name="invoice_debit_denied" states="paid" string="Debit Denied"/>
```

So the "Debit Denied" button is only shown when the invoice is Paid.

then, when you look at workflow/account_invoice.xml line 18, we find the signal "invoice_debit_denied" which go from account.act_paid to act_debit_denied. The workflow activity "act_debit_denied" will execute the method action_debit_denied(). This method is defined in models/account_invoice.py and raise an error message "You cannot set invoice <invoice_number> to state 'debit denied', as it is still reconciled." when test_paid() is True... which is always the case because the button "Debit Denied" is visible only when the state of the invoice is paid !

So, what is the use of the "Debit Denied" button on the invoice ? Can it lead to something else than an error message ? Maybe I mis-understand the use of this feature...

**Comment by StefanRijnhart** [comment]
Yes, the button feature is incomplete. It was probably added an afterthought and not properly tested after some refactoring when I developed this feature.

In our use cases, the invoice is set to Debit Denied after confirming a 'storno' bank statement line. The statement line, in which the amount is transferred back to the customer, is reconciled with the invoice, effectively unreconciling the invoice. This allows action_debit_denied to run successfully.

**Comment by alexis-via** [comment]
@StefanRijnhart 
When you install the module _account_direct_debit_, you get a _storno_ boolean field on the object payment.line, but not on the object account.bank.statement.line. How do you "confirm a storno bank statement line" ? Do you use another module for that ? If yes, where can I find this module ?

**Comment by alexis-via** [comment]
And the storno field on payment.line is readonly=True, so you can't set its value manually...
I guess you have another module to do the job that I haven't installed.

**Comment by sbidoul** [comment]
@alexis-via I don't remember having seen that during the refactoring, but I was probably partially blind to these things I did not fully understand. So it's very possible that it was overlooked when doing the 8.0 port. Have you looked in 7.0?

**Comment by alexis-via** [comment]
@sbidoul I don't fully understand those things either :) But I'm trying to... I'd like to better handle the scenario where a direct debit of an invoice has been rejected, and I have agreed with the customer to make a new direct debit of the same invoice (same player try again). And the 'storno' field seems specifically designed for that purpose.

**Comment by StefanRijnhart** [comment]
It's detected in some of the old banking addons filters. By the way, I remembered a possible use case for the button. If you unreconcile a move from an invoice, the invoice status remains unchanged (or it did in 6.1). You could then use the button to update the invoice state.

**Comment by pedrobaeza** [comment]
That option has been removed in last version, so I close.
