### ISSUE TITLE
Sepa Credit Identifier?

### ISSUE THREAD

**Issue by diezcode** [OCA/bank-payment#168]
I have a problem with the sepa credit identifier. When I'm putting the Sepa Creditor Identifier in the company settings and save it, it says: 

ValidateError

Error while validating constraint

Fehler

Invalid SEPA Creditor Identifier.

Any Help? I tested it with a spanish sepa identifier and it works.:

**Comment by pedrobaeza** [comment]
For which country are you putting the identifier?

**Comment by diezcode** [comment]
Switzerland like this for example:
CH07ZZZ00000012345

**Comment by sbidoul** [comment]
This CH07ZZZ00000012345 does not match the checksum algorithm implemented in the code.

Are you sure it is a valid sepa creditor identifier? As it is an example, it maybe the checksum is not correct.

**Comment by pedrobaeza** [comment]
Closing this as we have no answer
