### ISSUE TITLE
account_banking_payment_transfer breaks the hr_expense payment workflow

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#184]
When account_banking_payment_transfer is installed, hr_expenses never reach the paid state.

This is beacuse the reconciliation in account_banking_payment_transfer is not done using the account_move_line.reconcile() method [1]

https://github.com/odoo/odoo/blob/8.0/addons/hr_expense/hr_expense.py#L454

**Comment by pedrobaeza** [comment]
This is solved in https://github.com/OCA/bank-payment/pull/197
