### ISSUE TITLE
One of the records you are trying to modify has already been deleted (Document type: A generic banking mandate)

### ISSUE THREAD

**Issue by omar7r** [OCA/bank-payment#192]
Hi,

When you done a payment order with direct debit at least if you have the mandate repeated in more than one line, it fails with the error in subject.

In save_sepa() method when writing last_debit_date to mandate, it fails because object is repeated, I thought that recordsets works as set, but it accepts repeat values.

You can test it on odoo community runbot.

I can propose a PR with an if statement that check if mandate not exists in the recordset to add it, but the recorsets doesn't work as set?

Regards

**Comment by pedrobaeza** [comment]
No, recordset can contains duplicates, so they're not like sets, but more like lists (they also respect order)

**Comment by omar7r** [comment]
Hi Pedro,

Then, we have to fix the bug, because if you have a payment order with mandates repeated, it fails with the error in subject. I will try to propose a PR at the end of week.

**Comment by sergio-teruel** [comment]
Fixed in #195
