### ISSUE TITLE
[7.0] runbot is orange because of warnings in the logs

### ISSUE THREAD

**Issue by gurneyalex** [OCA/bank-payment#204]
WARNING: unable to set column hsbc_clientid_id of table payment_order not null !

WARNING: unable to set column type of table payment_mode not null !

 WARNING 3111478-7-0-2515ea-all openerp.osv.orm: No such field(s) in model account.payment.term.line: name (in module account_direct_debit: loading data/account_payment_term.xml)

**Comment by pedrobaeza** [comment]
Closing as old version and no PR.
