### ISSUE TITLE
[7.0] Camt parser broken because of missing attribute company_id

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/bank-payment#207]
File "/home/odoo/odoo/parts/bank-payment/account_banking_camt/camt.py", line 157, in parse_Stmt
    statement.local_currency = statement.company_id.currency_id.id
AttributeError: 'mem_bank_statement' object has no attribute 'company_id'

Because of https://github.com/OCA/bank-payment/pull/46/files

cc @bizzappdev @erwin-bas-solutions

**Comment by ploegvde** [comment]
Ok, we will have a look at it.

**Comment by ghost** [comment]
@StefanRijnhart 
Initially I added Euro as fixed currency but later @pedrobaeza commented "Better to use  statement.company_id.currency_id.id"
Right now I do not have any clue from where company_id is added into "mem_bank_statement".
For reference https://github.com/OCA/bank-payment/pull/46

Please suggest me how to process for the same.

**Comment by pedrobaeza** [comment]
Sorry, my fault, because I thought statement was a reference to `account.bank.statement` model. Fixed in https://github.com/OCA/bank-payment/commit/98bff921d827782dd5960cb4e4e0dcca953f5c4e
