### ISSUE TITLE
Error when trying to print bank mandate

### ISSUE THREAD

**Issue by drewes** [OCA/bank-payment#221]
I'm to print the mandate report but get an error:

QWebException: ""'account.banking.mandate' object has no attribute 'scheme'" while evaluating
"o.scheme != 'B2B'"" while evaluating
"translate_doc(doc_id, doc_model, 'partner_id.lang', 'account_banking_mandate.account_banking_mandate_document')"

Any suggestions?

**Comment by pedrobaeza** [comment]
You need to update the module in your DB.

**Comment by drewes** [comment]
Thanks for the quick reply.

I've just created a new database and directly installed the mandate module. I still get the same error?

Maybe some step I'm missing the setup?

**Comment by pedrobaeza** [comment]
Do you have _account_banking_sepa_direct_debit_ installed?

**Comment by drewes** [comment]
That was it.

I also had to install the Unidecode python library.

Works like a bomb.
