### ISSUE TITLE
Migration of account_banking_reconciliation and account_banking_make_deposit to V8 status ?

### ISSUE THREAD

**Issue by plamarche** [OCA/bank-payment#223]
Hi,
I would like to know if you have migrated those two powerful modules to V8 yet ?

Thanks in advance for your reply.

Pierre

**Comment by pedrobaeza** [comment]
That modules are not included in this repository, so the question doesn't make sense.

**Comment by pedrobaeza** [comment]
Sorry, my fault. I didn't see 7.0 branch. Look to this issue: https://github.com/OCA/bank-payment/issues/213
