### ISSUE TITLE
[8.0][account_banking_sepa_direct_debit] Not supported 2 identifiers for CORE and B2B

### ISSUE THREAD

**Issue by rafaelbn** [OCA/bank-payment#224]
module: account_banking_sepa_direct_debit
version: 8.0

**Steps to reproduce**
- After talking with banks they inform us that Companies must have 2 identifiers for CORE and for B2B direct_debit

**Current behavior**
- We have already only one indentifier

**Expected behavior**
- We must have 2 identifiers and choose one for CORE and the other for  B2B

I would like to know opinion of last contributors for resolving this new improvement. Thanks

cc @pedrobaeza @alexis-via @gurneyalex @sbidoul @rvalyi @rvalyi

**Comment by pedrobaeza** [comment]
Solution is to provide identifier at payment mode level.

**Comment by pedrobaeza** [comment]
The possible problem is if mixing both types on the same payment order.

**Comment by rafaelbn** [comment]
Bank says we cannot mix in 1 file 2 kinds of debit, if we have both CORE and B2B we must generate 2 separated files.

**Comment by pedrobaeza** [comment]
OK then, the solution is what I propose. I'll make a PR, although this will generate debate in the rest of the countries for sure.

**Comment by alexis-via** [comment]
@rafaelbn 
Have you found a document that says you must have one identifier for Core and another one for B2B ? I read many documents on Sepa direct debit to be able to write the OCA module, and I never read such thing.

**Comment by pedrobaeza** [comment]
@alexis-via, is not only a problem with CORE/B2B. All spanish banks use different suffixes for identifying you as a company, and even different suffixes by financial operation type (for example, for confirming or for credit transfer).

Do you have any problem if I make a PR moving initiating party identifier to the payment mode?

**Comment by alexis-via** [comment]
@pedrobaeza I'm not sure to understand your point about suffixes. Which field are you talking about exactly ?
If it is something specific to Spain, you should create a small module in the Spanish localisation. If it's something for all SEPA countries, let's put it in the generic module.
I have several customers using SEPA direct debit in production and very happy with it. I'm not against changing the datamodel, but only if it's generic for all countries.

**Comment by pedrobaeza** [comment]
The suffix is part of the initiating party identifier. For example, one of the possible form for this initiating party identifier is: `<country_code> + <vat-number> + '-' + <suffix>`.

But this also varies depending on the bank. I think we should put this on the generic model because it works for only one homogeneous identifier for all banks (you only have to put this unique identifier on each payment mode - a migration script will handle this automatically for the module upgrade -), or for non homogeneous one. This way, we avoid that several countries make the same modifications for the same purpose. It also makes easier the code to maintain, avoiding to add inheritance hooks or method overwritings.

**Comment by rafaelbn** [comment]
Now we are changing the identifier in the company, when B2B 101, when Core 100. This makes for each direct debit we have to go to the company and change value.

For us is OK so I close this issue.

**Comment by pedrobaeza** [comment]
Well, I don't think that's the solution, only a bad workaround. We need to have stored both, so I reopen.

**Comment by antespi** [comment]
This PR fixes this the problem too: https://github.com/OCA/bank-payment/pull/256

In this case, you can define a completely different identifiers per payment mode, but if not defined then company ones are selected. And no extra addon is needed.

Thanks for your review and opinion

**Comment by rafaelbn** [comment]
solved in https://github.com/OCA/bank-payment/pull/256
