### ISSUE TITLE
Direct debit doesn’ t change invoice status

### ISSUE THREAD

**Issue by jalzaga** [OCA/bank-payment#225]
When a customer invoice is included in a direct debit order and that order is done, the invoice status remains open. You can pay it directly or include it in a customer payment.

I checked that you cannot include it in another direct debit order, this is correct.

Besides, there is no journal create when the direct debit is confirmed. I guess you have to use necessarily  bank statement  to create the journal.

This affects to version 8

 Modules installed:  account_direct_debit and account_banking_sepa_direct_debit

**Comment by pedrobaeza** [comment]
That's not the current flow with v8. See https://github.com/OCA/bank-payment/tree/9.0/account_banking_payment_transfer for the current flow.

**Comment by jalzaga** [comment]
Thanks a lot Pedro. With reference to the transfer account in the payment mode, I don't see why it should be a regular account. In fact this is a “in payment management” account,  that normally belongs to the accounts receivable group.

**Comment by pedrobaeza** [comment]
Fixed in newer versions.
