### ISSUE TITLE
New export format for Dutch ING bank: MT940 IBAN

### ISSUE THREAD

**Issue by kvdb** [OCA/bank-payment#23]
According to the ING portal (Dutch):

```
Sinds 1 augustus 2014 kunt u transacties van uw rekening in nieuwe bestandsformaten met
IBAN downloaden. De huidige formaten (zonder IBAN) blijven tot 31 december 2014 beschikbaar.
Vanaf 1 januari 2015 zijn er drie formaten in Mijn ING Zakelijk: ‘MT940 IBAN’,
‘Kommagescheiden IBAN’ (JJJJMMDD) en ‘Tekst IBAN’.
```

It's listed among the supported formats:
https://www.ing.nl/zakelijk/betalen/sepa-europees-betalen/bestandsformaten/index.html

The format description itself:
https://www.ing.nl/media/ING_ming_mt940s_24_juli_tcm162-46356.pdf

The example at the end of the document should provide a nice testcase.
This time, the specs actually look remarkably like my actual transaction download.
It might solve any previous incompatibilities I encountered importing ING transaction dumps in older formats.

Is anyone already working on this or planning to?

**Comment by hbrunn** [comment]
That should be a pretty simple change in account_banking_nl_ing_mt940 - changing footer_regex might even be enough from glancing through the specification

**Comment by pedrobaeza** [comment]
Closing this as there's no PR involved

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
