### ISSUE TITLE
Missing field period_id causes compatibility issues

### ISSUE THREAD

**Issue by ecino** [OCA/bank-payment#24]
In account_banking/account_banking_view.xml, line 188, removing field period_id from bank statements can cause compatibility issues with other modules. One example is module account_statement_ext which also tries to remove it. Those two modules cannot be installed together.

One possible fix would be to hide it instead of deleting it.

**Comment by kenvac** [comment]
I agree with ecino. I had same problem couple of days ago. 
I would be nice to keep it hidden.

**Comment by StefanRijnhart** [comment]
I guess it does not hurt to hide it instead of remove it (please file a PR) but compatibility with other banking modules will always be problematic I think.

**Comment by ecino** [comment]
OK, I tried to write the patch, but the correction doesn't seem to work. When the field is invisible, it behaves like when it is removed.

I think if someone wants to install both modules together, he has to manually remove the code that deletes the field in one of the two modules. Does anybody see another better solution ?

**Comment by StefanRijnhart** [comment]
In account_banking, the period on the bank statement is meaningless. The period for each move is always derived from the accompanying statement line's date. If this is your gripe, it could probably be refactored out in a separate, optional module.

**Comment by pedrobaeza** [comment]
Without response for too much, so I close.
