### ISSUE TITLE
Mandates multicompany error

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/bank-payment#242]
The restriction rule Banking Mandate multi-company, gives an error when editing a partner bank account from a company A when that account has created a mandate from another company B. So it is impossible to create a mandate for each company without disabling the rule.
Possible solution: Uncheck the rule writte in Banking Mandate multi-company. But i'm not sure this is correct.

**Comment by pedrobaeza** [comment]
The best solution is to remove the default value for field company_id to leave the mandate unlocked by default, as the standard makes with the res.partner.bank model.

**Comment by DarioLodeiros** [comment]
But I think that the mandate must is linked with a company_id (because I should have a mandate for company!).
This solution is valid if it is introduced into the module and will not be overwritten , no?

**Comment by pedrobaeza** [comment]
Thinking again, you're right, but for doing it right, you have to include XML data that overwrites the rule by XML-ID, so that you don't lose changes on each update.

**Comment by pedrobaeza** [comment]
Thinking again, you're right. Can you please make a PR making that change?

**Comment by DarioLodeiros** [comment]
https://github.com/OCA/bank-payment/pull/243
