### ISSUE TITLE
Cannot compute 'Message Identification'

### ISSUE THREAD

**Issue by mgielissen** [OCA/bank-payment#247]
When I make a payment  "Export SEPA Credit Transfer File" from a payment order, I get this message:
Cannot compute the 'Message Identification'.

The Bank account and BIC are filled in.

**Comment by mgielissen** [comment]
The problem was solved after restarting odoo-server

**Comment by Jortolsa-S73** [comment]
pip install unidecode and restart odoo solved my problem
