### ISSUE TITLE
8.0 Cannot compute Sepa Creditor Identifier

### ISSUE THREAD

**Issue by sandrafig** [OCA/bank-payment#257]
When I try to make a direct debit order, Odoo raises the warning **"Cannot compute Sepa Creditor Identifier"**.

I have that identifier set correctly in the payment mode and also in the company settings, so I have no idea what's going on.

I know the identifier is the right one because I've used it many times before and every payment order was perfectly fine with my bank.

**Comment by pedrobaeza** [comment]
cc @antespi

**Comment by sbidoul** [comment]
@sandrafig @antespi is it related to #256  ?

**Comment by pedrobaeza** [comment]
Well, it can be, but we haven't faced this issue yet

**Comment by sandrafig** [comment]
I think it might be related because before the PR everything worked fine with the same identifier

**Comment by omar7r** [comment]
Hi,

Yes, the error is related to https://github.com/OCA/bank-payment/pull/256 the error line is:

```
self.generate_creditor_scheme_identification(
                creditor_scheme_identification_2_27,
                'self.payment_order_ids[0].mode.'
                'sepa_creditor_identifier or'
                'self.payment_order_ids[0].company_id.'
                'sepa_creditor_identifier',
                'SEPA Creditor Identifier', {'self': self}, 'SEPA', gen_args)
```

because the word 'or' is pasted to end of string, without any space between the 'or' and the next statement in the same string but in next line, it does not work because the "evals" function fails.

Regards.

**Comment by pedrobaeza** [comment]
Oh, we didn't see it because it doesn't get that point. So the solution is to put an space, isn't it?

**Comment by omar7r** [comment]
Yes

**Comment by pedrobaeza** [comment]
Please tell me the file where is located so I direct commit the fix or make a PR.

**Comment by omar7r** [comment]
account_banking_sepa_direct_debit/wizard/export_sdd.py
line: 228

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/bank-payment/commit/16310ff159d5797664b637c521be7eed5cba0440

**Comment by sandrafig** [comment]
Great!

**Comment by omar7r** [comment]
Thanks @pedrobaeza

**Comment by antespi** [comment]
Thanks @pedrobaeza, I missed that space.
