### ISSUE TITLE
Transifex translations to 8.0?

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/bank-payment#263]
I couldn't find this project in transifex for version 8.0 just 7.0.

How can I help to get this to work?

**Comment by pedrobaeza** [comment]
I have configured the .travis.yml for exporting to Transifex, so now you can find it.

**Comment by danimaribeiro** [comment]
Thanks.
Next time I know how to do it :)

**Comment by pedrobaeza** [comment]
For reference, here you have the commit that gets it: https://github.com/OCA/bank-payment/commit/7d289a8d9ba39d6af21c4ae02fc3ed31ea200d40

And here the list of secure: https://github.com/OCA/maintainer-quality-tools/issues/194
