### ISSUE TITLE
SEPA DIRECT DEBIT installation problems

### ISSUE THREAD

**Issue by hadessoul** [OCA/bank-payment#269]
HI,

I have this error when trying to install module

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: payment_mode_type - payment.mode.type]

Thanks

**Comment by pedrobaeza** [comment]
Not reproducible on runbot, so I close.
