### ISSUE TITLE
Credit transfers outside SEPA (international)

### ISSUE THREAD

**Issue by ghost** [OCA/bank-payment#271]
For now, only SEPA transfers are implemented in OCA/bank-payment. I am currently working on the standard pain.001.001.03 for international credit transfers. My client is still using Odoo v7.0, so this will be in 7.0 for now. The standard for international transfers is quite similar to transfers inside SEPA but with a few differences.

I am having an issue regarding that. The code base in account_banking_pain_base is very complicate for apperently no reason. The are a lot of parameters in almost every methods. The xml fields are evaluated with some kind of a context passed through "gen_args". Also, in the module account_banking_sepa_credit_transfer, there is a 200 long method. In other words, these modules are hardly maintainable and impossible to unit test.

So I made a first version of the international transfers but with a code structure different from account_banking_sepa_credit_transfer. I am wondering if people in OCA would still be interested.

**Comment by pedrobaeza** [comment]
Well, the situation will get better on v9 I think with a new architecture. Meanwhile, I think it can be interesting also this.

**Comment by ghost** [comment]
@pedrobaeza what changes on v9 ? Is there a pull request going on ?

**Comment by pedrobaeza** [comment]
In the Sorrento code sprint @alexis-via and @sbidoul worked on the new "bank-payment" infrastructure for v9. You can see some of the initial thoughts I made here: https://github.com/OCA/account-payment/issues/68.

We had an online meeting and I proposed to use report_xml module to export the XML file, like I do in the Spanish localization in this module. Look the file that generates the XML: https://github.com/OCA/l10n-spain/pull/331/files#diff-87cea79c8298160506b383aa68a226a0R1. Using QWeb syntax, we can inherit templates and change whatever we need.

The ongoing PR is here: https://github.com/OCA/bank-payment/pull/270

**Comment by ghost** [comment]
Thanks @pedrobaeza This answers my question. I will not propose my module to OCA. This would not be in the interest of anyone. I read the whole thread. The new bank-payment infrastructure looks good. For now, I am still not working with v9.0. When I get some time, i'll test it and try to give some feedbacks.

**Comment by alexis-via** [comment]
FYI, the support of credit transfer outside SEPA is already supported in v9 with my PR when the bank account use IBANs, but I haven't tested it in real life with a bank. We should also add support for ISO 20022 files with non-IBAN bank accounts (it is in my plans). If you want to add this feature in v8, it should not be very difficult.

**Comment by ghost** [comment]
@alexis-via thanks, indeed, this won't be very difficult. I will not contribute this because I don't want to have an ever lasting pull request. I am afraid that people won't be interested because they are focused on v9.

**Comment by alexis-via** [comment]
@dufresnedavid Yes, let's fine-tune this feature in v9. If you have a sample ISO 20022 credit transfer XML file with non-IBAN accounts that works in real life, I would be interested to see it. But the only change left in the code base should be the encoding of the non-IBAN account number in the XML ; that code is located in account_banking_pain_base.
