### ISSUE TITLE
[9.0] payment order: wizard domain bug

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#288]
How to reproduce:
- create a payment order
- click "create payment lines from journal items" to open the wizard
- populate the wizard to your liking
- in the move line list: clilck "add items": the list is filtered according to the wizard criteria
- in the wizard: click "add all move lines"
- in the move line list: clilck "add items" again: **the list is not filtered**

This is apparently due to the `populate` method returning a new action on the same transient record. In that case, the framework does not trigger `move_line_filter_change` to initialize the domain.

I don't know how to fix this.

cc/ @alexis-via @pedrobaeza @chrisdec

**Comment by pedrobaeza** [comment]
Is this still applicable?

**Comment by pedrobaeza** [comment]
@sbidoul is this still happening?

**Comment by j-zaballa** [comment]
The same issue occurs on v11.0. I don't know how to fix it either.

**Comment by j-zaballa** [comment]
Fix for v11: #561
