### ISSUE TITLE
[8.0] [BUG] account_banking_payment_transfer: payment order lines are duplicated

### ISSUE THREAD

**Issue by cubells** [OCA/bank-payment#291]
It's not a good decision to skip state 'done" in this line:
8.0/account_banking_payment_export/wizard/payment_order_create.py
because accounting user can reconcile payments a lot of days after payment order is sent. 

It's incorrect to assume that user reconcile payment lines immediately because if it's not so, company will pay or charge to other companies and that's the real problem.

**Comment by pedrobaeza** [comment]
I don't understand what your are talking about, Vicent. I'm using this module without problems for a long time, and covering all use cases. Chat me if you need some clarification.

**Comment by cubells** [comment]
https://github.com/OCA/bank-payment/blob/8.0/account_banking_payment_export/wizard/payment_order_create.py#L107

**Comment by cubells** [comment]
I see your discussion here #215 about this problem.

**Comment by cubells** [comment]
Ok. I understand the pros and cons.

I close this issue.
