### ISSUE TITLE
new format in SEPA XML Format

### ISSUE THREAD

**Issue by pasgou** [OCA/bank-payment#300]
[sepa xml.pdf](https://github.com/OCA/bank-payment/files/461289/sepa.xml.pdf)
Please see the change in xml format
to do for 8.0 and 9.0 please.

**Comment by pedrobaeza** [comment]
For being more informative, you should point here the changes.

**Comment by alexis-via** [comment]
I guess it is related to the new version of the Rulebook of the EPC.
The changes seems really minor, it is not difficult.

**Comment by pasgou** [comment]
There is a pdf file with my message
It's about the bank account in case it changes

Envoyé de mon iPhone

**Comment by alexis-via** [comment]
@pasgou Did you test my PR https://github.com/OCA/bank-payment/pull/303 to check that the changes I made are OK for the new rules ? If yes, could you approve the PR ?

**Comment by pasgou** [comment]
I'm sorry but no, i didn't test your PR. I don't have the situation
described by the new rule. My information was only there to be usefull to
the communitie.

Cordialement

Pascal GOUHIER

COPAGEX
Société d'expertise comptable
Membre de la Communauté des Experts en Gestion
8 Boulevard Albert Einstein
Parc de la Rivière
44300 NANTES

T : 02 40 58 56 49
F : 02 40 95 11 81

http://www.copagex.fr

2016-10-10 11:10 GMT+02:00 Alexis de Lattre notifications@github.com:

**Comment by alexis-via** [comment]
Implemented several months ago.
