### ISSUE TITLE
Cannot use type receivable or payable account as transfer account

### ISSUE THREAD

**Issue by jalzaga** [OCA/bank-payment#309]
Module account_banking_payment_transfer (in v 8) 

Impacted versions: 8, 9, 10

Steps to reproduce: In Payment mode. Transfer account

Current behavior: You can only select regular accounts as transfer account.

Expected behavior: Possibility to select other types such as accounts receivable or accounts payable. 
When you send a remittance to the bank, you should keep the amount in a transfer account until the bank pays, this transfer account belongs to the category of receivable or payable. As an example, in the Spanish Accounting these accounts belong to group 4 (Debtors and Creditors in commercial operations)

**Comment by pedrobaeza** [comment]
IMO we should allow any kind of account, as there are a lot of use cases where we can be interested in transfer the balance to another account.

@jalzaga, can you please make a PR changing this (for v8/v9)?

cc @alexis-via @sbidoul

**Comment by pedrobaeza** [comment]
Already fixed.
