### ISSUE TITLE
[7.0][account_banking_uk_hsbc] Multi currency invoice matching showing wrong residual

### ISSUE THREAD

**Issue by kenvac** [OCA/bank-payment#31]
Hello Team,

I noticed a problem in manual invoice matching when invoices are of same as bank statement currency but different company currency. I am experiencing this issue on account_banking_uk_hsbc module but looking at the code it seems its effecting very banking import module.

[Pre requisites]
- Install multi currency module
- Install account_banking_uk_hsbc
- Create separate bank journal having different currency than base currency
- Configure default bank import settings

[Assumptions]
- Base currency GBP
- Bank journal in EUR

[Steps to reproduce bug]
- Create an invoice in EUR 100
- Create another invoice in EUR 70. Doesn't matter if its from same parter
- Confirm both invoices
- Import bank statement with line 170 Euro
- Manually add two invoice and press match button in matching wizard
- You will notice where will be some residual amount on both statement line whilst should be zero.

The following is my recommendation. 

``` python
diff --git a/account_banking/wizard/banking_transaction_wizard.py b/account_banking/wizard/banking_transaction_wizard.py
index 0941f88..fcad8d9 100644
--- a/account_banking/wizard/banking_transaction_wizard.py
+++ b/account_banking/wizard/banking_transaction_wizard.py
@@ -197,10 +197,12 @@ class banking_transaction_wizard(orm.TransientModel):
                             cr, uid, todo_entry[1], context)
                     transaction_id = wiz.import_transaction_id.id
                     statement_line_id = wiz.statement_line_id.id
-
                     if len(todo) > 0:
+                        split_amount = move_line.debit or -move_line.credit
+                        if move_line.currency_id and move_line.currency_id == wiz.statement_line_id.currency:
+                            split_amount =  move_line.amount_currency
                         statement_line_id = wiz.statement_line_id.split_off(
-                                move_line.debit or -move_line.credit)[0]
+                                split_amount)[0]
                         transaction_id = statement_line_obj.browse(
                                 cr,
                                 uid,
```

Let me know if any more input is required. 

Regards,
K

**Comment by pedrobaeza** [comment]
Is this still happening? Why don't file a PR?

**Comment by pedrobaeza** [comment]
Closing as old version and no PR.
