### ISSUE TITLE
[10.0][account_banking_mandate_sale] IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Fenkiou** [OCA/bank-payment#332]
Steps to reproduce:
- Create a payment mode that require a banking mandate
- Create a sale order with the created payment mode

Current behaviour:
When selecting the payment mode, `IndexError: tuple index out of range` on this [line](https://github.com/OCA/bank-payment/blob/10.0) because my partner does not have any banking mandate.

Expected behaviour:
Not sure, wizard to create the mandate ?

**Comment by pedrobaeza** [comment]
Fixed in 4405e43548d7821cc254c615f7098f6a11841c9a
