### ISSUE TITLE
Status of  expenses is not always set to 'paid'  [Odoo 9 community]

### ISSUE THREAD

**Issue by DukeOfHammond** [OCA/bank-payment#333]
[Odoo 9 community]

Status of expenses is not always set to 'paid'  when the payment order is set to 'File correctly uploaded'
It happens mainly when the payment order was created with more than one expense in it (for the same partner).

Could someone who's already been working on this project fix it as soon as possible? My company would pay for the fix, you can contact me with an offer (how many time you'd need for this and how much it would cost), and we can discuss about it. 

Thank you very much!

**Comment by pedrobaeza** [comment]
Please provide a detailed step by step guide to replicate the error (you can try to replicate it in runbot), and put here, but we haven't found this problem till now. I close meanwhile.
