### ISSUE TITLE
Make 8.0 default branch and remove master

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-payment#34]
@gurneyalex I have pushed the new 8.0 from the greenified 7.0. Can you please remove master branch and make 8.0 default one?

**Comment by pedrobaeza** [comment]
Please someone of the board make this switch.

**Comment by pedrobaeza** [comment]
Can somebody with permissions attend this issue? There are people that are making PRs against master because of this.

**Comment by gurneyalex** [comment]
sorry for my late reaction, I'm a bit overwhelmed by customer projects... 8.0 is now the default branch.

**Comment by gurneyalex** [comment]
and master has been removed.

Closing the issue.

**Comment by pedrobaeza** [comment]
Thanks!
