### ISSUE TITLE
account_payment_mode 10.0 - cash payment type?

### ISSUE THREAD

**Issue by BzMB** [OCA/bank-payment#341]
Hi, 

Thanks for your work on migrated this module.

The business idea is "track" also the payment mode = cash at customer,so and invoice level.

Is there any way,configuration or additional module to install in order to create a new payment mode called "cash" linked to the journal cash?

Thanks in advance.

**Comment by pedrobaeza** [comment]
Payment modes are manually created, so I don't understand the question.

**Comment by BzMB** [comment]
Hi,

Thanks for your reply, let me try to clarify our point

There's no cash journal option during the creation of a new payment mode called cash.

See the attached screenshot
![account_payment_modes_no_cash_journal](https://cloud.githubusercontent.com/assets/20208755/23211731/5f8e5fc6-f8fb-11e6-8520-0d8e771f030b.png)

**Comment by pedrobaeza** [comment]
OK, but for your purpose (which is only to inform in the invoice about a cash payment mode), you can fill that value with whatever value you want.

**Comment by pedrobaeza** [comment]
Closing as answered.

**Comment by xabispacebiker** [comment]
Hello, I also have the same question as @BzMB and in my case I don't want to just inform the invoice about the mode of payment. I understand that the payment method is a field that I can use to select the preferred payment method for a partner and that it should be dragged to other models (sales, invoices, etc.) and when I mark the invoice as paid, It should automatically select the default or preferred payment. Therefore, if a customer for any reason use to pay in cash, we are not able to keep track of it. So I think @BzMB's point is correct and there should be a way to select cash journals in the payment methods form.
