### ISSUE TITLE
Data migration of payment order from 8.0 to 10.0

### ISSUE THREAD

**Issue by adrienpeiffer** [OCA/bank-payment#348]
Hi Guys,

I try to migration a project that contains payment order from 8.0 to 10.0
Considering the changes in this module, this requires huge migration scripts.

Has anyone ever worked on the subject ?

Thanks,

Adrien

**Comment by pedrobaeza** [comment]
Migration scripts have already been done. Check this as a summary: https://github.com/OCA/OpenUpgrade/pull/656#issuecomment-266319202

**Comment by adrienpeiffer** [comment]
Thanks a lot Pedro !
