### ISSUE TITLE
IBAN Account check

### ISSUE THREAD

**Issue by Aivenho** [OCA/bank-payment#359]
[all versions] In Odoo standard functionality account check with `is_iban_valid()` is done only for accounts with type `IBAN Account`, type `Regular Account` is not checked. But in your account_banking_pain_base module check is set for all the account types. That creates problems with the payment export is partner is from outside EU. 
Other issue is with EU payments not in EUR. They are regarded as international payments, not SEPA, so they should automatically get switched to that, other way ir shows error during import in bank system.

**Comment by alexis-via** [comment]
In Odoo v9 and v10, 'sepa' is a compute boolean field, cf https://github.com/OCA/bank-payment/blob/10.0/account_banking_pain_base/models/account_payment_order.py#L26
Read the code of the method, you will understand better how it works.

About IBAN, the behavior is not the same between odoo v8 and odoo v9/v10. Please tell us exactly on which version you have a problem.

**Comment by Aivenho** [comment]
I use odoo v8.

**Comment by alexis-via** [comment]
The scenario of non-SEPA payments (i.e. currency != EUR or account type != IBAN) is well supported on v9 and v10, but I'm not sure it's properly supported on v8.

**Comment by pedrobaeza** [comment]
Closing as old version. Any PR amending whatever incorrect behavior there can be considered any way.
