### ISSUE TITLE
[10.0]Payment mode not reported in invoice when using the subscription module

### ISSUE THREAD

**Issue by Maurice67205** [OCA/bank-payment#385]
on Version 10 when generating an invoice from the subscription module , the payment mode of the customer is not automatically inserted in the invoice

**Comment by pedrobaeza** [comment]
With https://github.com/OCA/bank-payment/commit/d7e0b19fdd4fbe280b2283d42bc7b2a5d826a173 and https://github.com/OCA/bank-payment/commit/8f40c26ba5661bc3f5b8ce11683855f612f5a2c7 it shouldn't happen. Did you upgrade your code?

**Comment by pedrobaeza** [comment]
Closing as no answer
