### ISSUE TITLE
[6.1,7.0] account_banking - wrong entries in split bank transaction if invoice partially paid

### ISSUE THREAD

**Issue by bodi000** [OCA/bank-payment#390]
Hello,

I know these are old versions, but I need a bit of help, as I still use the account_banking module.
Task: import and reconcile bank statement (camt).

I have a case where one banking transaction (a credit card invoice) covers multiple invoices. One of the invoices is partially paid. While doing the split, the split_off function is asked to use move_line.debit, (which of course is the total amount of the invoice) not invoice.residual which would be the correct amount.

banking_transaction_wizard.py:223/208
`statement_line_id = wiz.statement_line_id.split_off(
                            move_line.debit or -move_line.credit)[0]`

While I think this is a bug, I would like your opinion, especially @StefanRijnhart .

Thank you in advance
B

**Comment by StefanRijnhart** [comment]
Yes, I agree. The split should be bounded by the residual of the selected matching move lines, but also by the remaining amount on the statement line. If only we had known what we know now :-(

**Comment by pedrobaeza** [comment]
Any PR for these old versions? If not, I don't want to keep opened eternal issues that are not going to be fixed as people don't work already in that versions.

**Comment by pedrobaeza** [comment]
Closing meanwhile.

**Comment by StefanRijnhart** [comment]
Reopening as it is not fixed. @pedrobaeza we clearly agree on this. I find no harm in keeping known issues open so that people who run into the same issue have a point of reference, and people who consider using these modules know what they get into.

**Comment by pedrobaeza** [comment]
No, @StefanRijnhart, as said, this is not going to be fixed ever, and I don't want to have opened them. We must triage issues the same as Odoo does.

**Comment by StefanRijnhart** [comment]
@pedrobaeza it's clear we don't agree. @OCA/core-maintainers can you help us settle this discussion?
