### ISSUE TITLE
interaction with the account_batch_deposit and check payment module

### ISSUE THREAD

**Issue by a-willem** [OCA/bank-payment#391]
When using payment_mode configured with a transfer account, the suite behaves well when associated with SEPA direct debit orders.

However, when used to register payments by check, or when receiving wire transfers, they "payment" fuctionality doesn't seem to acknowledge this set-up. Hence, when registering a check, instead of writing in the transfer account, it is written in the bank account.

**Comment by pedrobaeza** [comment]
Sorry, but they are different modules, and obviously check registering works the way it's intended, not the way this module does. If you want to have that feature, you will need to develop an extension to register check system.
