### ISSUE TITLE
 	[8][account_banking_sepa_direct_debit]

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/bank-payment#403]
After reinstalling a production database in a new server, SEPA direct debit does not work any more.

When pressing buttons /MAKE PAIMENT/GENERATE , this error appears.

`
Odoo Warning
Cannot compute the 'Message Identification'. `
Thank you

**Comment by pedrobaeza** [comment]
Sorry, this is something in your configuration. Check SEPA identifiers.

**Comment by fgarcia-humanoide** [comment]
Identifiers are the same in both servers. I dont think it is the cause.
