### ISSUE TITLE
Code error in account_payment_sale

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#42]
I'm reporting a bug in my own code : in the 7.0 branch, in account_payment_sale/model/sale.py line 41, we have the following code:

 partner.customer_payment_mode.id or False,

We should NOT have a coma at the end of this line. When we run the module in Odoo 8.0, it will crash when creating a sale order via a call to create because addons/sale/sale.py in odoo 8.0 silently plays the on_change and then it will try to create {"payment_mode_id: (False,)}, when leads to a crash

**Comment by pedrobaeza** [comment]
As I have updated 8.0 modules to new API in #35, error doesn't apply in that branch.

**Comment by alexis-via** [comment]
This was merged in the OCA/7.0 branch a long time ago !
