### ISSUE TITLE
[10.0] payment orders not compatible with bank statement matching

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#428]
When you pay through a payment.order with a payment mode to configure to put the counterpart move line on the bank account, the bank statement reconciliation does not work.

**How to reproduce**

- Create a payment mode with the option of creating transfer move the the bank account.
- Create and confirm a payment order for amount A.
- Create a bank statement with amount -A on the same bank account.
- Reconcile

**Expected behaviour**

- a blue line is visible corresponding to the payment

**Current behaviour (the issue)**

- the blue line does not appear

The problem comes from Odoo that explicitly checks that account.move.line->payment_id is set for showing blue lines for reconciliation. Since our bank.payment.line is not an account.payment this does not work.

The Odoo code is impossible to extend to work around this.
https://github.com/odoo/odoo/blob/02b9dbac3250abd942e8f9f9e06621ef829315fe/addons/account/models/account_bank_statement.py#L567

Now I'm wondering: would it make sense for bank.payment.line to actually be an account.payment?

@alexis-via @pedrobaeza have you seen the same issue?

**Comment by sbidoul** [comment]
cc/ @chrisdec @adrienpeiffer

**Comment by pedrobaeza** [comment]
Yes, we saw it a lot of time ago: https://github.com/odoo/odoo/issues/18972, but unfortunately Odoo doesn't consider our approach.

We have made a PR in OCB for restoring the previous behavior: https://github.com/OCA/OCB/pull/678

**Comment by sbidoul** [comment]
Thanks for the pointers Pedro.

**Comment by pedrobaeza** [comment]
Other solution is to create an auxiliary account.payment register when transferring balances. What do you think?

**Comment by sbidoul** [comment]
@pedrobaeza could be yes. If we link that account.payment to the transfer move it should work.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by sbidoul** [comment]
@pedrobaeza I do not plan to work on this short term. The OCB fix was fine with me (at least the previous version of it). I suggest to keep this issue open for tracking the problem.
