### ISSUE TITLE
[11]Error when creating bank mandate

### ISSUE THREAD

**Issue by jalzaga** [OCA/bank-payment#446]
When you try to create a bank mandate the system does not allow it and gives the following message: 
Error while validating constraint
'res.partner.bank' object has no attribute 'name'

To reproduce it: Go to a customer, create a bank account for this customer or use an existing one, edit the bank account and add a direct debit mandate, fill in the fields, save, and when you try to save the bank account it gives the error message.
This has been tested in runbot.

**Comment by JordiBForgeFlow** [comment]
On what version?

**Comment by jalzaga** [comment]
version 11 @jbeficent

**Comment by JordiBForgeFlow** [comment]
cc @rgarnau can you try to reproduce?

**Comment by jalzaga** [comment]
@jbeficent  @rgarnau  you can see it on runbot, just try to create for instance a new mandate in the Camptocamp's bank account.

**Comment by rgarnau** [comment]
@jalzaga can you check if this PR fixes the error you mention? https://github.com/OCA/bank-payment/pull/447

**Comment by jalzaga** [comment]
cheked #447  NOT successful  @rgarnau @jbeficent

**Comment by pedrobaeza** [comment]
Final fix is correct, so I close this.
