### ISSUE TITLE
[10] make it possible to select vendor refunds in the wizard "Create payments lines from journal items"

### ISSUE THREAD

**Issue by yung-wang** [OCA/bank-payment#456]
It is not possible to select vendor refunds in the wizard "Create payments lines from journal items". 
But if you don't use the wizard and select it directly in the tab Transactions in the main screen, than you can add refunds. And this works perfectly as long as the total payment for this vendor is positive.

It is strange that in the wizard you can't but in the main screen you are able.

If you create a solution, please migrate it also to V11.

**Comment by pedrobaeza** [comment]
Sorry, but that's an uncovered feature that we don't want if everything is not controlled (it depends on the total amount, and even then, I'm not sure about the reconciliations). If you want to develop that feature, a PR is always welcome.
