### ISSUE TITLE
SEPA Credit Transfer is not compatible with all swiss banks.

### ISSUE THREAD

**Issue by ghost** [OCA/bank-payment#465]
The Züricher Kantonalbank (https://www.zkb.ch) does not follow the ISO standard and implements the required (optinal) tag <InstrId> as mandatory instead.
pain.001.001.03.ch.02 states that <InstrId> is required and multiplicity is documented as 0..1.
I got the answer from ZKB that they need the element to give a response with transaction id in case of error. That would help the user to identify the problem more easily.

See page 31 of Swiss Implementation Guidelines ( https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf ) and XSD (pain.001.001.03.ch.02.xsd) is mentioned in same document on page 52 ( https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct-examples.zip )
My exported XML-pain file was unsuccessfully tested on ZKB test platform ( https://testplattform.zkb.ch ).
Other swiss banks returned no problems, just hints that element <InstrId> should be used.

&#60;CdtTrfTxInf&#62;
..&#60;PmtId&#62;
....&#60;InstrId&#62;XXX&#60;/InstrId&#62; &#60;!-- required by ZKB --&#62;
....&#60;EndToEndId>XXX&#60;/EndToEndId&#62;

**How to reproduce**

Create a SEPA payment order.
Create xml-pain file.
Upload xml-pain file to validation platform of Zürich Kantonalbank ( https://testplattform.zkb.ch ).

**Expected behaviour**

Exported pain file can be validated by all swiss banks.

**Possible Fix**
Add statement for "InstrId" like for "EndToEndId". I recognized that line.name is unique because is is composed of "L" and the bank_statement_line.id. Therefore it might be sufficient to just copy that part of the code and change the tag name.
https://github.com/OCA/bank-payment/blob/9.0/account_banking_sepa_credit_transfer/models/account_payment_order.py#L129-L133

**Comment by pedrobaeza** [comment]
You should use specific modules in OCA/l10n-switzerland for that.

**Comment by ghost** [comment]
I do. But those modules do not change the writing of the xml-pain file.
They just change the way some numbers are generated and grabs another XSD for validation.
https://github.com/OCA/l10n-switzerland/blob/9.0/l10n_ch_pain_base/
https://github.com/OCA/l10n-switzerland/blob/9.0/l10n_ch_pain_credit_transfer/

**Comment by pedrobaeza** [comment]
Then put there the issue, as it's something local to Swiss.

**Comment by ghost** [comment]
Thanks

**Comment by joko300370** [comment]
> Züricher Kantonalbank ( https://www.zkb.ch ) tidak mengikuti standar ISO dan menerapkan tag (optinal) yang diperlukan sebagai wajib sebagai gantinya. 
> pain.001.001.03.ch.02 menyatakan bahwa diperlukan dan multiplisitas didokumentasikan sebagai 0..1. 
> Saya mendapat jawaban dari ZKB bahwa mereka membutuhkan elemen untuk memberikan respons dengan id transaksi jika terjadi kesalahan. Itu akan membantu pengguna untuk mengidentifikasi masalah dengan lebih mudah.
> 
> Lihat halaman 31 Pedoman Penerapan Swiss ( https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf ) dan XSD (pain.001.001 .03.ch.02.xsd) disebutkan dalam dokumen yang sama di halaman 52 ( [https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines- ct-examples.zip](https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct-examples.zip) ) [File](https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct-examples.zip)
> XML-pain saya yang diekspor tidak berhasil diuji pada platform pengujian ZKB ( https://testplattform.zkb.ch ). 
> Bank swiss lainnya kembali tidak ada masalah, hanya petunjuk bahwa elemen harus digunakan.
> 
> <CdtTrfTxInf>
> ..<PmtId>
> ....<InstrId>XXX</InstrId> 
> ....<EndToEndId>XXX</EndToEndId>
> 
> **How to reproduce**
> 
> Create a SEPA payment order.
> Create xml-pain file.
> Upload xml-pain file to validation platform of Zürich Kantonalbank ( https://testplattform.zkb.ch ).
> 
> **Expected behaviour**
> 
> Exported pain file can be validated by all swiss banks.
> 
> **Possible Fix**
> Add statement for "InstrId" like for "EndToEndId". I recognized that line.name is unique because is is composed of "L" and the bank_statement_line.id. Therefore it might be sufficient to just copy that part of the code and change the tag name.
> https://github.com/OCA/bank-payment/blob/9.0/account_banking_sepa_credit_transfer/models/account_payment_order.py#L129-L133

saya menggunakan penambahan account BNI 46 BNINIDJASMG 0954380327-USD joko purwanto karena standar pembayaran gogle pay kami tidak layak dan saya penguna asli joko300370 dan data saya sangat akurat  BNI 46 BNINIDJASMG 0954380327-USD joko purwanto number passport B8967514 Republik of Indonesia on behalf joko purwanto legal .
