### ISSUE TITLE
[9] Payment order creation fails with 'structured'

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/bank-payment#495]
I'me getting this error:

> bank-payment-9.0/account_payment_order/models/account_move_line.py", line 34, in _prepare_payment_line_vals
>     ref2comm_type[self.invoice_id.reference_type]
> KeyError: u'structured'

It seems that the 'structured' reference type is added by account_payment_order module,
but there is not correspondance between reference_type 'structured' on invoice and communication type on payment line given by the metchod account_payment_line.py:

>     def invoice_reference_type2communication_type(self):
>         """This method is designed to be inherited by
>         localization modules"""
>         # key = value of 'reference_type' field on account_invoice
>         # value = value of 'communication_type' field on account_payment_line
>         res = {'none': 'normal'}
>         return res

Do I miss the module that is supposed to add the structured communication type?

Thanks in advance

**Comment by pedrobaeza** [comment]
Can you make the PR fixing the problem?
