### ISSUE TITLE
Unable to install module "account_banking_pain_base" because an external dependency is not met: No module named unidecode

### ISSUE THREAD

**Issue by alexhuijser** [OCA/bank-payment#505]
Hi, I get message:
Unable to install module "account_banking_pain_base" because an external dependency is not met: No module named unidecode
But I'm running Windows. What to do?
Thx

**Comment by pedrobaeza** [comment]
I recommend you to switch to Linux because there will be a lot of uncomfortable things using Windows like this one. You should put in the Odoo installation python lib folder that dependency (but I don't know exactly how).

Any way, it's not a problem of the module.
