### ISSUE TITLE
[v7] Paid more does not set invoice to paid status

### ISSUE THREAD

**Issue by ploegvde** [OCA/bank-payment#52]
I have invoice of the amount of 850. On bank statement i receive a payment of 1000. Now when i confirm the bankstatement line, the invoice does not get the paid status. On the invoice is registered a paymnet of 1000. This is not correct.

The invoice should be reconcilled with the payment and the diff (150) should stay open by default on the debtors account. It should be the same as using the pay botton on the invoice.

**Comment by ploegvde** [comment]
Fix is on the way.

**Comment by pedrobaeza** [comment]
Is the error still there?

**Comment by pedrobaeza** [comment]
Closing as no answer.
