### ISSUE TITLE
[12.0][BUG] account_payment_mode

### ISSUE THREAD

**Issue by alexayllon** [OCA/bank-payment#544]
I think I find a bug on payment modes.
If I create a payment mode with a variable link to a several banks, when I get the debit order I can't select the bank. 
![captura de pantalla 2019-01-25 a las 16 21 39](https://user-images.githubusercontent.com/22914905/51754716-5183a300-20bd-11e9-958e-409d9869e6fa.png)

**Comment by pedrobaeza** [comment]
I have just tried and seems to work without problems:

![seleccion_017](https://user-images.githubusercontent.com/7165771/52157962-c34a8680-2693-11e9-9a32-bb4c3b94ac20.png)

![seleccion_018](https://user-images.githubusercontent.com/7165771/52157965-d198a280-2693-11e9-9f37-aa88f36f60ad.png)

But I got the problem: when you save and come back later to the payment order, the journal domain is reset and the list becomes empty.

Investigating to see the source of the problem.

**Comment by pedrobaeza** [comment]
Temptative solution in #548
