### ISSUE TITLE
[11.0] Create bank account number directly in supplier invoice sets the account to the main company not to the partner

### ISSUE THREAD

**Issue by altoch** [OCA/bank-payment#545]
With sepa bank transfer payment mode on supplier invoice, it appears a selection field that allows to create a bank account number  to pay the bill via sepa transfer. If you create it directly in the invoice menu, then the account is set to the main company as the owner of the account.
If the account is created from the partner menu, it's done properly.
Way I fixed, disallow to create account numbers from the invoice form, overriding the view setting partner_bank_id as a widget="selection" 
I guess there's missing in some point the declaration of the default id via a context to the generated account, which I'm not able to find where is the problem in the code.

**Comment by pedrobaeza** [comment]
Just add `'default_partner_id': partner_id` in the context for getting the proper partner in the bank account. Would you do the PR?

**Comment by altoch** [comment]
I will try, I end up with adding to the view account_payment_partner.invoice_supplier_form:
  <attribute name="context">{'default_partner_id':commercial_partner_id}</attribute>

PR: https://github.com/OCA/bank-payment/pull/546

**Comment by altoch** [comment]
It also happens at purchase order level. 
supplier_partner_bank_id  assigns the account owner to the company not to the supplier on the purchase order form.
I created another PR https://github.com/OCA/bank-payment/pull/547 account_payment_purchase
The bug which is  the same case.
