### ISSUE TITLE
Non SEPA bank account on mandate and payment order.

### ISSUE THREAD

**Issue by angelmoya** [OCA/bank-payment#609]
An user put an account number wrong, so this account number was no SEPA.

Then you can create mandate for this non SEPA account.

You can set this bank account and this mandate on invoice with sepa payment mode.

Then if you create a payment order including this invoice with non sepa account, you can generate file to upload in bank.. but file is wrong because the file lose SEPA label on file, and then in the bank file is processed but payment are reject.

What do you think about:
- In mandate, add type = SEPA on bank account domain.
- In payment method add field "SEPA Bank Account Required" like "Bank account required" or "Mandate required" but more restrictive.

**Comment by pedrobaeza** [comment]
OK about mandate domain, but only when mandate type is SEPA.
