### ISSUE TITLE
[12.0][BUG] Installing account_payment_purchase failed

### ISSUE THREAD

**Issue by AngelCamacho** [OCA/bank-payment#613]
When installing account_payment_purchase using **pip**, an unsatisfied requirement error is raised:

`pip install --pre --upgrade odoo12-addon-account-payment-purchase==12.0.1.0.0.99.dev3`

It raises the following error:
` ERROR: Could not find a version that satisfies the requirement odoo12-addon-purchase-stock (from odoo12-addon-account-payment-purchase==12.0.1.0.0.99.dev3) (from versions: none)
ERROR: No matching distribution found for odoo12-addon-purchase-stock (from odoo12-addon-account-payment-purchase==12.0.1.0.0.99.dev3)`

It seems that it's searching for `purchase-stock` requirement as an OCA addon when it should be searched for as an Odoo addon.

**Comment by sbidoul** [comment]
That was resolved 4 years ago in https://github.com/acsone/setuptools-odoo/commit/c2415e14760d2fff625c5dca8140419feee1b553 :sweat_smile:
