### ISSUE TITLE
[v7] Invoice is linked to wrong account

### ISSUE THREAD

**Issue by ploegvde** [OCA/bank-payment#62]
When a invoice has no tax and we import a bank statement, on the matching process the invoices matches first on amount. Because there is no tax, the amount of both entries of the invoice are the same. Now the created bank statement line can get the wrong account. It should always be a payable or receivable account. We have to add a check for that.

**Comment by ploegvde** [comment]
Fix is on the way

**Comment by pedrobaeza** [comment]
As the PR is also closed, I close this one.
