### ISSUE TITLE
account_banking_sepa_direct_debit: code SEPA missing on xlm (export)

### ISSUE THREAD

**Issue by anajuaristi** [OCA/bank-payment#623]
Hi... we had an issue from a customer using this module in V8 and now trying to go to V12.

The XML obtained in V12 is refused on bank due to this error:
"Código incorrecto (distinto de SEPA)"

Compairing both files on V8 and V12, we see the difference:

V8:
`       <PmtTpInf>

        <SvcLvl>
          <Cd>SEPA</Cd>
        </SvcLvl>

        <LclInstrm>
          <Cd>CORE</Cd>
        </LclInstrm>

        <SeqTp>FRST</SeqTp>

      </PmtTpInf>
V12
`  <PmtTpInf>

        <LclInstrm>
          <Cd>CORE</Cd>
        </LclInstrm>

        <SeqTp>FRST</SeqTp>

      </PmtTpInf>`

Just the lines are missing on file.V8:
`       <PmtTpInf>

        <SvcLvl>
          <Cd>SEPA</Cd>
        </SvcLvl>`

So.. the question is... the tag is missing because there is an issue on creating the XML file? Or it's a missconfiguration issue? 
I'm just reporting to not forget it. We will continue investigating. I will update when we have got more info.

**Comment by pedrobaeza** [comment]
This is because there is a bank account that is not IBAN.

**Comment by anajuaristi** [comment]
Ok. Thank you
We will try to export a file for a single customer having IBAN account and we will write it here
