### ISSUE TITLE
[12.0] account_banking_sepa_direct_debit: Mandates don't print properly

### ISSUE THREAD

**Issue by ghost** [OCA/bank-payment#626]
Steps to reproduce in Runbot:
Invoicing > Payments > Banking mandates
Select some records
Print > Sepa mandate
The report is printed like this:
![1](https://user-images.githubusercontent.com/25029267/63338078-6f0ea780-c342-11e9-866f-3ddded285ad4.png)
I have seen that it was happening on V11 too and it was fixed here::
https://github.com/OCA/bank-payment/pull/444

**Comment by rafaelbn** [comment]
Hi @gelo-landoo could you please make a PR to fix this issue? Thanks

**Comment by ghost** [comment]
@rafaelbn sorry, but I'm not a developer. I don't know how to do it. I can make the revisions but not to develop.
