### ISSUE TITLE
account_banking_mandate migrations openupgradelib dependency

### ISSUE THREAD

**Issue by enricostano** [OCA/bank-payment#632]
Hi,

is there any reason why [this](https://github.com/OCA/bank-payment/blob/11.0/account_banking_mandate/migrations/11.0.2.0.0/pre-migration.py#L4) dependency is not declared in [setup.py](https://github.com/OCA/bank-payment/blob/11.0/setup/account_banking_mandate/setup.py)?

I guess we could avoid issues like https://github.com/OCA/bank-payment/issues/614

Thanks!

**Comment by pedrobaeza** [comment]
Because that's only for migrations, not for the normal usage of the module.

**Comment by enricostano** [comment]
Hi! Thanks for your reply, I'm just curious: upgrading the module is not considered normal usage in Odoo modules development?

**Comment by pedrobaeza** [comment]
Yes, but if you upgrade, you must install in your environments `openupgradelib`. It's always the same library. Consider your environments to have Odoo requirements.txt + openupgradelib (and always the version in GitHub, not in pypi).

**Comment by enricostano** [comment]
> Consider your environments to have Odoo requirements.txt + openupgradelib

OK, thanks.

> (and always the version in GitHub, not in pypi)

Why? I'm using https://pypi.org/project/openupgradelib/ but I see the latest release is from 2018. We only use pypi to install Python packages, is there any reason pypi is not up to date?

**Comment by pedrobaeza** [comment]
Yes, because it's very dynamic and packaging it under fixed versions is not practical. You can use pip though:
```
pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
```
