### ISSUE TITLE
[11.0][12.0] account_payment_order_return

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/bank-payment#633]
When the module "account_payment_order_return" is installed, I think it is wrong that to see the accounting accounts 431000, 401000, etc. and to be able to make remittances of promissory notes to post, you must check the "include move lines from returns" to see those accounts, if not mark the notes can not be selected.

**Comment by ghost** [comment]
I realized after installing this module the expenses created by expenses module cannot be added to payment orders. The journal ittems don't appear when you try to import them from the button "Create Transactions from Move Lines".
I realized that it happens on V11 at least.
