### ISSUE TITLE
[11.0] account_banking_sepa_direct_debit: Error when generate new payment file

### ISSUE THREAD

**Issue by vpcarlos** [OCA/bank-payment#642]
Generate payment file button in payment order throws:

OCA/bank-payment/account_banking_sepa_direct_debit/models/account_payment_order.py", line 110, in generate_payment_file
    key = (line.date, priority, categ_purpose, seq_type, scheme)
UnboundLocalError: local variable 'seq_type' referenced before assignment

**Comment by pedrobaeza** [comment]
You have a mandate that is generic, not SEPA specific one.
