### ISSUE TITLE
Multicompany environmen should allow having different mandates for different companies

### ISSUE THREAD

**Issue by anajuaristi** [OCA/bank-payment#644]
Hello
We have got a case impacted by this constraint

https://github.com/OCA/bank-payment/blob/6b3f2b733d3bd86292ba9b3e7044093359159799/account_banking_mandate/models/account_banking_mandate.py#L135

Question is that we have got a customer working in a multicompany environment, so the partner itself could sing different mandates for same bank account number.

Example:
John Doe, whos company is a group header "Group" containing company1, company2 and company3
John Doe, has got the bank account "Bank account John"
he wants to autorize company1 and company2 "Group" to use "Bank account John" 

This constraint is not allowing to do that since mandate company will always be different from John Doe's company.
I tried several configurations... like, duplicating the bank account or seting null on John Doe's company but I did not succed.

Our proposal is to remove the constraint from this object in order to be able to cover the user case. What do you think? Do you see any big impact on it? 

@oihane @pedrobaeza @alexis-via 
Thank you!!

**Comment by pedrobaeza** [comment]
Similar question in #637
