### ISSUE TITLE
[11] account_banking_mandate: Cannot change Mandate on payment

### ISSUE THREAD

**Issue by tundraconsulting** [OCA/bank-payment#648]
Hello,

I've found this issue:
I create a Customer with two bank accounts and assign a different SEPA mandate for each one.
Create 2 different invoice for this Customer and add to payment order. If I want to change the bank account for one of these invoices, the mandate won't be updated and I cannot choose manually.
So, I cannot sabe the payment order because of the mandate is not valid for changed bank account.

Please, check my screenshots.

Thank you.
![2](https://user-images.githubusercontent.com/54932942/68298134-e679ea80-0098-11ea-983e-d14f8c1d5331.jpg)
![1](https://user-images.githubusercontent.com/54932942/68298137-e679ea80-0098-11ea-851d-616a92c020a5.jpg)

**Comment by pedrobaeza** [comment]
This is because you haven't checked in your associated payment method the check "Mandate required".

**Comment by tundraconsulting** [comment]
Great! Thank you very much for your support. I close the issue.
