### ISSUE TITLE
Add renamed project to coveralls

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-payment#66]
As the project has been renamed, coveralls need explicitely to enable the service for the new project name. This only can be done by OCA board members. 

@jgrandguillaume, can you please do it?

**Comment by yvaucher** [comment]
To be configured from here I guess ?
https://coveralls.io/r/OCA/banking

**Comment by pedrobaeza** [comment]
Yeah, that's it

**Comment by pedrobaeza** [comment]
This was done already.
