### ISSUE TITLE
[12.0] account_banking_mandate update question

### ISSUE THREAD

**Issue by microsound1** [OCA/bank-payment#665]
Hi all,

I have a windows installation of odoo 12 with account_banking_mandate - v 12.0.1.0.0
On Apps - Update I can see a newer version of this module account_banking_mandate - v 12.0.2.0.0

When I try to update I get a ModuleNotFoundError: No module named 'openupgradelib'

Also the same error for  account_payment_order update from - v 12.0.1.0.0
Local: 12.0.1.3.0 | Remote: 12.0.1.3.0 

Is there anything I can do? 
Thank you.

**Comment by pedrobaeza** [comment]
Just install openupgradelib Python library in your system.

**Comment by microsound1** [comment]
Thank you so much, on windows I had difficulties to find the correct command, but finally it worked:

Opened CMD Navigate to the python directory C:\Program Files (x86)\Odoo 12.0\python and issued
"python -m pip install openupgradelib"
