### ISSUE TITLE
What is SEPA?

### ISSUE THREAD

**Issue by kittiu** [OCA/bank-payment#673]
Hi, I am trying to make sense in this repo. It seem that many modules here is related to SEPA. If SEPA is for EU (right?) does it means that most modules are not usable else where?

What is SEPA anyway :)

**Comment by pedrobaeza** [comment]
https://en.wikipedia.org/wiki/Single_Euro_Payments_Area

Yes, mostly for EU. Any way, only `*pain*` and `*sepa*` modules are for that. The rest can be used for other payment methods.

**Comment by kittiu** [comment]
Thank you @pedrobaeza
