### ISSUE TITLE
account_payment_order with around 1500 payment lines

### ISSUE THREAD

**Issue by wpichler** [OCA/bank-payment#676]
Hi all,

i do use the account_payment_order and account_banking_sepa_direct_debit module for a customer - which does around 1500 payment lines at once.
SEPA File generation did worked quit fine - small modifications for austria have been necesarry - but rest was ok.
The problem now is - that i can not set the "File uploaded" state for the payment order - because it seems to not be able to work on such a big payment order.
I've looked at the code - and changed a small thing to get it working. 

In account_payment_order/models/account_payment_order.py is the function generate_move - which does then call the _create_reconcile_move function with all payment lines grouped by a hashcode. In the original code it does call the _create_reconcile_move function with all blines - this did not work - it never finished. 
I've changed this to call the _create_reconsile_move function for every bline in blines - this does work in a reasonable time - and the result also seems to be correct for me.

So - is there anything why it will get called with the complete set of blines instead of every bline of its own ?

**Comment by pedrobaeza** [comment]
Which Odoo version?

**Comment by wpichler** [comment]
12

**Comment by pedrobaeza** [comment]
It's weird that we have that performance decrease in v12 for doing things together instead record per record. Have you tried in a fresh environment? I think the idea of doing everything together is for having the reconciliation information together.

**Comment by wpichler** [comment]
doing it in bulk should be faster - but in this case there seems to be some problems...

If i do read the code correct - then the difference is:
When doing it in bulk - it will create one account.move with many move lines. This move then gets reconcilled against the invoices (and i think in this process there is the problem). So you have one move - with many reconcilations.
With my "patch" / workaround you get one account.move per payment line. This does also work.

It should maybe reflect the settings in batch_booking. If batch_booking is enabled - then create one account.move with many lines. If batch_booking is not enabled the create one account.move per payment line ?

**Comment by pedrobaeza** [comment]
But these options are already available in the module... You can group by payment line or by payment date if I don't remember bad.

**Comment by wpichler** [comment]
Correct - but these options currently only affects the generated sepa file - and does instruct the financial institute to create only one debit line - or several debit lines. But does not affect the odoo side...
So it would be consistent to also let it affect the odoo side

**Comment by pedrobaeza** [comment]
You should be mixing things:

![Selección_005](https://user-images.githubusercontent.com/7165771/74335159-d6f6f580-4d9b-11ea-852f-f411f68da219.png)

This is for the generated journal entries.

**Comment by wpichler** [comment]
You are correct - now i can see it. This option does affect the hascode which gets generated. So it does affect the grouping of the blines - with One move per payment line it will create a hash based on payment line id - so one move per payment line - else it will create one move per date...

I've not seen this - thanks @pedrobaeza 

Does an OCA Documentation Project exists ? ;-)

**Comment by pedrobaeza** [comment]
The idea is to collect all of this at module README level. You can do a PR for improving it based on your experience.
