### ISSUE TITLE
account_payment_order: Credit, Debit, Balance fields in Journal Items Tree view

### ISSUE THREAD

**Issue by gaikaz** [OCA/bank-payment#683]
This is more of a question/suggestion type of issue.
As I kept getting asked by accountants "Where did the Credit and Debit columns go?"
Only after investigating for a while, we figured out the hacky way those fields are being replaced in module `account_payment_order` by Python code first introduced with this commit:
https://github.com/OCA/bank-payment/commit/e8ebf4861aa680d73afe5722e771f4bd1bf81b9a#diff-b151cbbb56ca373280f17e2731f3928cR124

From the commit and code comments, I understand that "Balance" fully replaces "Credit/Debit". But the way this is done is not very elegant and very frustrating to find, as no actual XML is editing the `account.move.line` Tree view.

So here are my questions:
1. Could we add a very clear note in the module description about how this module affects the tree views? 
2. Why was this done via Python in the first place? Is this simply the case of sacrificing "readability" and extensibility for less code?
3. As some accountants are very stubborn about seeing Credit/Debit columns side by side, it being their comfort zone, could we maybe add a couple of `if's` in the code, to make this optionable?
4. Lastly, how come this is not affecting community Runbot, where the module is installed? Am I missing something obvious here? I tested this on a fresh DB with demo data where I only installed this module and it did change the Journal Items tree view.

cc: @pedrobaeza @JordiBForgeFlow

**Comment by pedrobaeza** [comment]
The problem is that the balance/debit/credit is not a trustable source for this: the residual amount is. And I don't see the problem. The view is only for payment orders, so I see it correct.

**Comment by gaikaz** [comment]
> The view is only for payment orders

Alright, this makes me think there is something wrong with my deployments then.
From what I see, this affects the Tree view in **Invoicing > Accounting > Journal Items**

What views should this be modifying then?

**Comment by pedrobaeza** [comment]
This line:

https://github.com/OCA/bank-payment/commit/e8ebf4861aa680d73afe5722e771f4bd1bf81b9a#diff-b151cbbb56ca373280f17e2731f3928cR93

should limit to only payment orders.

As always, are you able to reproduce the problem in runbot?

**Comment by gaikaz** [comment]
Thank you @pedrobaeza for taking time to respond. I know how busy you are.

Like I formulated in 4th question in the issue desc. It's not affecting runbot, I can't explain why.

I understand, that this line should check the module with `self._module`, which for some reason is `account_payment_order` for me in Journal Items menu on my localhosts, production, test servers.
There really must be something wrong with how I deploy my servers.

I will try to install Odoo from an official package and only add this module (+dependencies), just to see if that works. There could also be a bug here.

So let's not close the issue just yet, until I fully figure this out and write here, what I find.
Is that Ok? 🙂

**Comment by gaikaz** [comment]
@pedrobaeza 
I figured it out. `self._module` cannot be trusted. My theory is, that it is set to the last module that modifies the model.
The runbot works because it has all modules from this repository installed, and because `account_banking_mandate` also modifies the `account.move.line` and directly depends on `account_payment_order`, the `self._module` is probably set to it.

Basically, to reproduce on runbot:
1. Uninstall `account_banking_mandate`
2. Go to Invoicing > Accounting > Journal Items
3. The Tree view list will now be affected.

**Comment by pedrobaeza** [comment]
Well, I didn't create that code, so I can't say exactly, but I haven't found this in any customer. Do you have any fix for this?

**Comment by gaikaz** [comment]
Sadly, no :pensive: But I would rather suggest a refactoring of that code instead of fixing it.
Wouldn't it be cleaner to rewrite in simple XML's? Python implementation doesn't feel very OCA'ish.

Also, doesn't this mean that this code either always works or doesn't at all?
I mean, the views it intended to modify are probably not being modified anyway?

In the meantime, I will be installing `account_banking_mandate` (I guess it's needed for us anyway).

**Comment by pedrobaeza** [comment]
Yes, TBH I don't know the motivation for doing this this way, but XML explicit views seems better. I guess this is for preserving other possible custom modifications to that view, that primary mode will lose. @JordiBForgeFlow you were the original author of this. Can you tell us?
