### ISSUE TITLE
[12.0] Problems if I create a mandate from invoice or payment order

### ISSUE THREAD

**Issue by Lopsanz** [OCA/bank-payment#688]
You can create a mandate from here (in draft mode) and this one is added to bank payment line. Then an error occurs when I confirm the payment order.

https://github.com/OCA/bank-payment/blob/979261ce0f15cde89344a7d4de4c06a2c629246c/account_banking_mandate/views/bank_payment_line_view.xml#L15

I think to put  'options="{'no_create': True}" ' in this field would be enough

**Comment by pedrobaeza** [comment]
Or an onchange over `mandate_id` filling possible missing bank account in payment line.

**Comment by Lopsanz** [comment]
A draft mandate must not be able to be used in a payment order, because there is not a check in payment order validation.
When you create a mandate from the payment line it is in draft mode, but is also put into the payment line.
I think the origin of the problem is in batch invoice validation. Mandate_id is mandatory at formview level, but not at listview.

**Comment by pedrobaeza** [comment]
Well, all this logic can be included for keeping the consistency. Is there any way to put a mandate even  if not validated although you don't create it through this quick shortcut? If so, then it should be prevented as well.

**Comment by Lopsanz** [comment]
Yes. Making an account invoice we could have the same problem.
https://github.com/OCA/bank-payment/blob/979261ce0f15cde89344a7d4de4c06a2c629246c/account_banking_mandate/views/account_invoice_view.xml#L15

**Comment by pedrobaeza** [comment]
Well, I think it's acceptable to include a draft mandate in the invoice, as long as you don't confirm a payment order with it. I think the control should be done confirming the payment order.
