### ISSUE TITLE
[13.0] User can't "Add to payment/debit orders" the invoices from tree view (account_payment_order)

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/bank-payment#701]
I was reviewing https://github.com/OCA/bank-payment/pull/686 and I realized that this functionality is not working for V13 as it was in previous versions.

User can't add invoices to payment/debit orders from the tree view but it's still possible to add them one by one from the form view. IMHO it was an interesting feature that should be maintained.

Do you think that would be appropriate to suggest a [FIX] for that?

Thx.

**Comment by pedrobaeza** [comment]
Yeah, I think it should be simple to re-add and it's the definition of the action in the XML.

**Comment by HaraldPanten** [comment]
Closing this issue as the FIX PR has been merged
