### ISSUE TITLE
account_payment_partner addon v13 report_invoice_payment_mode

### ISSUE THREAD

**Issue by crazyshark2** [OCA/bank-payment#703]
When install give this error

`report_invoice_payment_mode
[view_id: 1701, xml_id: none, model: none, parent_id: 656]" while parsing /opt/odoo/custom/account_payment_partner/views/report_invoice.xml:2, near
<odoo>

**Comment by crazyshark2** [comment]
can anyone know this??

**Comment by SolidGlenn** [comment]
Also have this problem on branch 13.0
`odoo.tools.convert.ParseError: "Element '<xpath expr="//p[@t-if='o.invoice_payment_term_id']">' cannot be located in parent view

Error context:
View `report_invoice_payment_mode`
[view_id: 2627, xml_id: n/a, model: n/a, parent_id: 901]" while parsing /opt/odoo/oca-addons/bank-payment/account_payment_partner/views/report_invoice.xml:2, near
<odoo>
    </odoo>`
