### ISSUE TITLE
[12.0]account_payment_order_return

### ISSUE THREAD

**Issue by javierjcf** [OCA/bank-payment#718]
https://github.com/OCA/bank-payment/blob/dc8a3ed1e0739c4b40ab59bfeb160541ca24dc22/account_payment_order_return/wizards/account_payment_line_create.py#L18

I think this is a bug. If i dont check the self.include_returned field, the condition is true, so  ('invoice_id.returned_payment', '=', False) is added to the domain.
I think is a problem, because a lot of account.moves.lines are not linked to an invoice, so invoice_id.returned_payment is False BUT because invoice_id is False, so this moves are not found.
I need to check always the include_returned field in order to found the moves.

Im not sure about all, but is a problem that already found

**Comment by colmeirin** [comment]
Hello, I can confirm I experienced the same behaviour which is very odd with move lines that are not linked to invoices such as payrolls payments or expenses.

**Comment by pedrobaeza** [comment]
Please add a PR that modifies the domain this way:
```python
domain += [
    '|',
    ('invoice_id', '=', False),
    ('invoice_id.returned_payment', '=', False)
]
```

**Comment by colmeirin** [comment]
Fix has been merged. I think this can be close now @javierjcf
