### ISSUE TITLE
[13.0] [RFO] account_payment_order: Migration to 13.0 kwown issue

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/bank-payment#719]
As invoices are now account.moves, user must set a "reference" field in invoices, or "communication" field in bank.payment.lines wouldn't be set. If communication fields are not set, an error is occurring as a mandatory field hasn't been set.

In previous versions, communication field was inherited from invoice numbers if I'm right. But now, it inherits the "reference" field.

Do you think that any info should be shown in invoices when user selects a payment mode related to a "sepa_credit_transfer" payment method? I was thinking about that, as I don't think we should set "reference" field as mandatory.

**See attached images:**

<img alt="Captura de pantalla 2020-06-09 a las 12 55 19" width="1331" src="https://user-images.githubusercontent.com/32449357/84139759-bf313480-aa50-11ea-9886-69aa6edf3c11.png">

**This is my suggestion:**

<img alt="Captura de pantalla 2020-06-09 a las 12 44 47" width="1422" src="https://user-images.githubusercontent.com/32449357/84139839-e7b92e80-aa50-11ea-87cb-b4e96a8f98e8.png">

What do you think?

**Comment by pedrobaeza** [comment]
Module was incorrect as stated, and the proposed solution is not correct. The code snippet pointed by @ValentinVinagre is more on the track. Probably the culprit is the used reference type.

**Comment by HaraldPanten** [comment]
> Module was incorrect as stated, and the proposed solution is not correct. The code snippet pointed by @ValentinVinagre is more on the track. Probably the culprit is the used reference type.

closing then
