### ISSUE TITLE
[12.0] account_payment_partner: bank is never set on customer invoice

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/bank-payment#720]
After that commit https://github.com/OCA/bank-payment/pull/655 I can't get my bank account automatically set on invoice.
I would expect at least to have the bank set if the payment mode (account_payment_mode) is set on the invoice and it has a fixed bank.

**Comment by pedrobaeza** [comment]
That's the idea, to let the payment order algorithm to work.

**Comment by Martronic-SA** [comment]
The context here is with customer invoices. There is no payment order for customer invoice

**Comment by pedrobaeza** [comment]
Yes, there is. Call it debit order if you want.

**Comment by Martronic-SA** [comment]
Yes of course if you use the direct debit system but in most of cases the company has one bank account and that last should be set automatically on the customer invoice. The customer makes the paiment transfert manually on the given bank reference.
The bank company is used to generate the QR bill reference for exemple.
(We are located in Switzerland, maybe things are different in other countries)

**Comment by pedrobaeza** [comment]
`account_payment_partner` already includes a modification in the invoice report for showing the bank account with the preferences set in the payment mode. For Switzerland QR, you need to add specific hook code or re-enable that bank account filling in your custom Swiss module, unless you find a way to compatibilize both the problem depicted in the PR and your requirement.

**Comment by Martronic-SA** [comment]
Ok I understand the problem with potential conflict with SEPA direct debits. but when the company doesn't use direct debits, the standard behavior should be left in place. maybe check if customer payment mode is SEPA DD and if not, set the bank account the same as for supplier invoice? @carlosdauden

**Comment by pedrobaeza** [comment]
I don't think it should be conditioned by SEPA DD, but the previous behavior was simply not correct, assigning a bank account that is not going to be used at all and can be incorrect (for example, if the partner changes the bank account meanwhile). That's why it's better to leave it blank, and fetch it dynamically when it's going to be used (in SEPA DD), or in your case, for the QR. IMO, you should modify the QR generation to take it dynamically as well.

**Comment by enricostano** [comment]
We ended up creating a new module: https://gitlab.com/coopdevs/account_payment_auto_partner_bank 
Not sure it's the best approach... but it solved our use case.

**Comment by Martronic-SA** [comment]
@enricostano We ended up the same, ours is named "account_payment_partner_default" ...
Probably not the best approach also.
We are using payment modes only for supplier invoices et get the default bank for customer invoices without payment mode.

**Comment by enricostano** [comment]
@Martronic-SA do you think it would be useful to merge the 2 modules?

cc/ @cesarlr

**Comment by yvaucher** [comment]
Currently the Swiss QR module doesn't depend on `account_payment_mode` as it is an official report in `l10n_ch`.

Furthermore, for the v10 backport I kept the same logic as in v13 to try to be payment-mode-agnostic.
If needed we can add a glue module when both are installed as IIRC Odoo don't provide the proper hooks to be able to get the bank account info even from OCA modules.

But this might be an issue outside of the `l10n-switzerland` project scope.

**Comment by pedrobaeza** [comment]
Is there an option to compatibilize both problems in the base module?
