### ISSUE TITLE
[13.0]account_payment_order: missing  buttons "Add to Debit Order" and "Add to Payment Order"

### ISSUE THREAD

**Issue by kurogeek** [OCA/bank-payment#721]
module: account_payment_order
version: 13.0

Here is the code for those two buttons. This code located on account_payment_order/views/account_invoice_view.xml
```
<button
    name="create_account_payment_line"
    type="object"
    string="Add to Debit Order"
    groups="account_payment_order.group_account_payment"
    attrs="{'invisible': ['|', '|',
        ('payment_order_ok', '=', False),
        ('state', '!=', 'open'),
        ('type', 'not in', ('out_invoice', 'out_refund'))
/>
<button
    name="create_account_payment_line"
    type="object"
    string="Add to Payment Order"
    groups="account_payment_order.group_account_payment"
    attrs="{'invisible': ['|', '|',
        ('payment_order_ok', '=', False),
        ('state', '!=', 'open'),
        ('type', 'not in', ('in_invoice', 'in_refund'))
    ]}"
/>
```
However, in Odoo version 13 invoices(account.move) no longer have state "open". There are only 3 states which are "draft", "posted" and "cancel". So, this means that the buttons will never appear to be seen at any state on Odoo version 13.

**Current behavior**
Those two buttons never appear due to attribute `('state', '!=', 'open')`.

**Expected behavior**
The buttons should visible at some state.

**Comment by pedrobaeza** [comment]
Can you please do the PR changing this?

**Comment by kurogeek** [comment]
Yes, I can. But I don't know which state should I use to make the buttons appear.

**Comment by pedrobaeza** [comment]
I have just checked the code and you are using wrong version, as this is fixed:

https://github.com/OCA/bank-payment/blob/a1db1b42d3f735c684dc7240a10238cff359b520/account_payment_order/views/account_invoice_view.xml#L26

https://github.com/OCA/bank-payment/blob/a1db1b42d3f735c684dc7240a10238cff359b520/account_payment_order/views/account_invoice_view.xml#L37
