### ISSUE TITLE
[12.0] Missing requirement.txt for the bank-payment repository?

### ISSUE THREAD

**Issue by BT-rmartin** [OCA/bank-payment#735]
I've seen this, and at least _unidecode_ is not part of odoo requirements. 

https://github.com/OCA/bank-payment/blob/893fe25b280a053aeb9ce53dd9e1d4fa914a40e1/account_banking_pain_base/__manifest__.py#L19

Wouldn't be needed to create a requirements.txt file in this repository with that?

**Comment by pedrobaeza** [comment]
It seems so. Please fill a PR adding it.
