### ISSUE TITLE
[13.0] Account payment order grouped creditors entry 

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/bank-payment#738]
**Steps:**

1. Create a payment order for 3 supplier invoices from the same creditor (3 x 100USD)
2. Payment mode is to group transactions
3. Create and validate the payment 
4. Reconciliation booking will contain 4 lines (300 debit / 100 x 3 credit)
5. Unreconcile the invoice from the from view

**Behavior:**
All invoices are unreconciled because complete reconciliation is cancelled.

**Desired behavior:**
Reconciliation booking will contain 6 lines (100x3 debit / 100 x 3 credit)
Only one invoice is unreconciled when unreconciling

**Comment by pedrobaeza** [comment]
Change configuration for not grouping. This is already implemented. Just configure it.

**Comment by CasVissers-360ERP** [comment]
But not grouping will also post one bank statement line / payment per invoice?

**Comment by pedrobaeza** [comment]
If I don't remember bad, you have the option to select group by payment date.

**Comment by CasVissers-360ERP** [comment]
@pedrobaeza 
I tried both. 

**For grouping see:**
http://3438847-13-0-b1d3cd.runbot3.odoo-community.org/web#id=4&action=394&model=account.payment.order&view_type=form&cids=1&menu_id=140

Unreconcile on of the invoices from the from view and you will see all other invoices are set to unpaid as well. This since they are in the same reconciliation .

**For non grouping see:**
http://3438847-13-0-b1d3cd.runbot3.odoo-community.org/web#id=2&action=394&model=account.payment.order&view_type=form&cids=1&menu_id=140

The issue here is that we will get 3 bank statement lines one per invoice. The supplier and the controlling team won't like this.

What am I missing?

**Comment by CasVissers-360ERP** [comment]
**Another non-grouping move per date same issue:**
http://3438847-13-0-b1d3cd.runbot3.odoo-community.org/web#id=3&action=394&model=account.payment.order&view_type=form&cids=1&menu_id=140


The offsetting account should always be split for account.move (per invoice). Else the reconciliation will always be done on all invoices.

**Comment by pedrobaeza** [comment]
I reopen as I don't have time to check that, but I haven't found this yet in my customers.

**Comment by CasVissers-360ERP** [comment]
Fixed by Odoo in https://github.com/odoo/odoo/commit/55a5eaf367aaaf9421d2ee003f359ffef7ffae99

**Comment by pedrobaeza** [comment]
Thanks for the follow-up and sorry for not being able to cooperate more.
