### ISSUE TITLE
[13.0] Successfully uploaded payment orders are not compatible with bank statement matching

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/bank-payment#779]
I think this issue is related to that old stuff: https://github.com/OCA/bank-payment/issues/428

That was mentioned by @sbidoul and was solved in newer versions. Thankfully the issue is still open to keep that as a reminder.

95% Same use case and expected behaviour as before:

**How to reproduce**

- Create a payment mode ([sepa_direct_debit] SEPA Direct Debit for customers (inbound) payment method) with the option of creating transfer move to the bank account. (Offsetting Account = Bank Account)
- Create a customer invoice with amount X.
- Add that invoice to a debit order.
- Follow the usual steps for confirming the Debit Order, generate the file, and finally mark the file as successfully upload.
- Create a bank statement with amount X.
- Try to reconcile the bank statement line with the invoice.

**Expected behaviour**

- a blue line should be visible corresponding to the payment, so user should be able to reconcile the statement with the invoice.

**Current behaviour** (the issue)

- the blue line does not appear, so... user has a bank statement line that can't be reconciled.

In previous versions (at least in V12), that was already solved. Even if the debit order was marked as successfully uploaded, user was able to reconcile the bank statement line with the blue line related to each invoices.

Haven't you faced that issue in V13 as well? I tested that in runbot and blue lines are still not appearing.

@pedrobaeza

**Comment by pedrobaeza** [comment]
Just fw-port #678 to 13.0 in OCB.

**Comment by HaraldPanten** [comment]
I thought that was included in V13 OCB by https://github.com/OCA/OCB/commit/65b8da8b50c167e68945aafafd4c5e3f71ff8e44

**Comment by pedrobaeza** [comment]
Ah, I didn't remember. Then it should work...

**Comment by HaraldPanten** [comment]
OCA runbot works with OCB, right?

**Comment by pedrobaeza** [comment]
Nop, with vanilla Odoo

**Comment by HaraldPanten** [comment]
THX, Pedro

Maybe that's why the issue is still failing in runbot as well.

Any other alternative for fixing the problem in the own module? Or that should be included in OCB?

I mean... Probably Odoo is not going to fix that, so... can we do anything else instead of adding this fix in every OCA/OCB versions?

**Comment by pedrobaeza** [comment]
No without losing performance having to perform operations 2 times.

**Comment by sbidoul** [comment]
At some point I had this idea to investigate if our `bank.payment.line` could inherit `account.payment`. But that's a big and risky change that and we always end up applying the small Odoo patch for customers who need payment orders *and* blue lines in bank statements (which is not that often because most customer end up using "payment in transit" accounts anyway).

**Comment by HaraldPanten** [comment]
THX @sbidoul @pedrobaeza 

In the end, we decided to apply the patch. Closing the issue
