### ISSUE TITLE
Python library not installed: unidecode

### ISSUE THREAD

**Issue by albertogallegoir** [OCA/bank-payment#787]
I cannot install the Account Banking PAIN Base Module or Account Banking SEPA Direct Debit because the phyton library is missing. I work in Windows and I don't know how to get it.

Thank you

**Comment by pedrobaeza** [comment]
Put that Python library in your Odoo installation folder in the proper place, but that's out of scope of this issue tracker.

**Comment by albertogallegoir** [comment]
> Coloque esa biblioteca de Python en su carpeta de instalación de Odoo en el lugar adecuado, pero eso está fuera del alcance de este rastreador de problemas.

Y dónde consigo esa biblioteca? y cuál es el lugar adecuado para instalarla?

**Comment by pedrobaeza** [comment]
Please ask that things in the Odoo forums.

**Comment by albertogallegoir** [comment]
Gracias!
