### ISSUE TITLE
[Question] Decouple payment.order of payment.order.line

### ISSUE THREAD

**Issue by mileo** [OCA/bank-payment#794]
Hi,

Currently instant payments have become increasingly important. Consequently, the generation of batch payment orders ends up reducing the speed of operations, or creating a redundancy of data: when a payment order has only one line.

Would it be possible to make the payment lines less dependent and can be processed without depending on a payment order itself?

**Comment by pedrobaeza** [comment]
I think you should use core models for that (`account.payment`, `payment.transaction`...).
