### ISSUE TITLE
Generated XML files have disappeared

### ISSUE THREAD

**Issue by proptrading** [OCA/bank-payment#800]
Hello

I'm running Odoo 12 OCA. I've been working well with SEPA Direct Debit module for creation XML files but at some time download option step when XML file is generated have dissapeared. To reproduce my steps:

1) Generate an invoice and go to create_account_payment_line
2) Go to Confirm payment (draft2open)
3) Go to Generate payment file (open2generate)
Expected result: 
"Download Click here to download the generated file: ****.xml"
Current response:
Payment ID, details..but the generated file is unable to download. Next step generated2uploaded

Where can I find the generated file? Not only for this transaction, where is the history of all generated XML sepa files?

Thanks

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in OCA runbot.

**Comment by HaraldPanten** [comment]
You can find them as attachments

**Comment by pedrobaeza** [comment]
Closing meanwhile further evidence of bug is provided.

**Comment by proptrading** [comment]
> You can find them as attachments

Could you share the route to find these attachments? Where are all generated files available for download?
