### ISSUE TITLE
[14.0] account_payment_order migration issue

### ISSUE THREAD

**Issue by ph-obs** [OCA/bank-payment#808]
Hey guys,

not sure if this is the right way to communicate this so please pardon me if it isn't. If it is though I would like to talk about one issue I am facing while upgrading a customer of ours from Odoo 12 to Odoo 14 on Odoo.sh. I have included the latest version of account_payment_order in the project but everytime I try to make a new build on Odoo.sh the built-in Odoo.sh code validation fails throwing the following error:

`module account_payment_order: Each post-migration file must have a "migrate(cr, installed_version)" function`

I'm not super deep into these migration files so I don't know how to handle this error exactly. Is this a bug that you guys need to fix or am I doing something wrong here?

Thanks for your support.

**Comment by pedrobaeza** [comment]
Include `openupgradelib` in your pip dependencies, but the latest version available:
```
git+https://github.com/OCA/openupgradelib.git@master
```
