### ISSUE TITLE
[12.0] account_payment_order with 2000 payment lines

### ISSUE THREAD

**Issue by benj-filament** [OCA/bank-payment#811]
Hi all,

I have a problem to set the "File uploaded" state for the payment order with 2000 payment lines.

**Steps to reproduce:**
Create a SDD payment mode, check _Generate Accounting Entries On File Upload_ and select _One move per payment date_
Create a debit order, select SDD payment mode
Create 2000 payment lines (with the same payment date)  
Confirm payments and generate XML File
Click on _File uploaded_

**Current behavior:**
With _One move per payment date_ option checked, __create_reconcile_move_ function creates a move and tries to reconcile each payment line using _reconcile_ and __reconcile_lines_ functions from _account.move.line_ model.
The problem is that with 2000 payment lines, it takes 5 seconds to reconcile 1 payment line...
It is faster when there are fewer lines (about 1 second per line). It's also faster with _One move per payment line_ option.

Is there a way to generate and reconcile debit order faster ?

Thanks

**Comment by frdmar** [comment]
Same problem here.
After some debugging I noticed the [account.move.create() on _create_reconcile_move](https://github.com/OCA/bank-payment/blob/12.0/account_payment_order/models/account_payment_order.py#L484) is very slow: 11.05s on 156 lines.
Also the [reconcile()](https://github.com/OCA/bank-payment/blob/d8ab63d95981e8809acd44911bcea4b67547a473/account_payment_order/models/bank_payment_line.py#L160) function of the bank_payment_line is quite slow: about a seconds for single line.

**Comment by pedrobaeza** [comment]
This is something outside the scope of this module, as it's standard Odoo. Go to upper versions, where this has been optimized. Closing as nothing to be done here.
