### ISSUE TITLE
[13.0] Posting invoices without mandatory field set.

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/bank-payment#838]
I'm not sure if this issue is due to the account_payment_partner module or if it should be addressed in another module/repository. Probably it's a general issue and not only because of invoice_partner_bank_id field when it's mandatory.

Steps to reproduce the malfunction:

1- I create a customer payment method that has the bank account as required. We can try the sepa_direct_debit payment method.

2- I create a sale order with a payment mode in which the bank account is required (we need the account_payment_sale module).

3- I validate the quotation.

4- I create the invoice.

5- I select the draft account move from the tree view and I post it.

Result: I have a posted invoice, with an empty required field (invoice_partner_bank_id).

Consequences: The user cannot send that invoice by email, it is not possible to return that to draft ...

Imagine the problem when the user has done it with a large amount of invoices... 

You can test my flow in runbot.

What do you think that would be the best way to keep the restriction to post the entries, even if they're posted using the tree view action? @pedrobaeza @JordiBForgeFlow @kittiu @sbidoul @StefanRijnhart 

**See my video:**

![Video issue](https://user-images.githubusercontent.com/32449357/126686976-6928b4d0-3f3b-42ff-b0bc-1dcfe6c491bb.gif)

**Comment by pedrobaeza** [comment]
It's mandatory only on view, not on DB. Uncheck the field in the payment method that says "Bank account required".

**Comment by HaraldPanten** [comment]
> It's mandatory only on view, not on DB. Uncheck the field in the payment method that says "Bank account required".

THX for your reply.

So, if we want users to fill this field (for example for payment orders) It's better to keep it as not mandatory for avoiding this use cases.

I know that setting this field as not required is valid to set the invoices back to draft again, but for forgetful users, it's useful to keep it as mandatory as well.

What a dilemma...

**Comment by pedrobaeza** [comment]
I always set it to False, and let the system to dynamically select the invoice when adding the invoices on the payment/debit order.
