### ISSUE TITLE
[14.0] account_payment_order: payment order not created form a vendeor bill.

### ISSUE THREAD

**Issue by AmmarOfficewalaSerpentCS** [OCA/bank-payment#839]
Steps to reproduce in Runbot:
Invoicing > Vendor > Bill
Select some records
Click on an action Add to Payment/Debit Order
Click on a create button   
You got a warning and here it is a warning:
https://drive.google.com/file/d/1g1M_i4f74DIif6Dx_Dujjsj4SM1--DzX/view

**Comment by pedrobaeza** [comment]
That's because you haven't put the reference in the vendor bill.
