### ISSUE TITLE
Better use move_id.ref or move_id.payment_reference in payment order ?

### ISSUE THREAD

**Issue by TeoGoddet** [OCA/bank-payment#848]
In my understanding, the payment_reference field should be sent as the payment reference instead of the ref field.
Am I wrong ?

**Comment by pedrobaeza** [comment]
I would say it depends in:

- It's an invoice or an entry.
- It's for customer or for supplier.

If you want to propose a pull request handling this, it would be appreciated.

**Comment by TeoGoddet** [comment]
I could do the PR,
But i need to know what are the "business" and odoo rules to follow

**Comment by pedrobaeza** [comment]
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

**Comment by TeoGoddet** [comment]
i meant the exact generic accounting meaning of those names
and the exact odoo meaning of those fields

**Comment by pedrobaeza** [comment]
It depends on the version, the field is called for saying the type of move is `move_type` (v14 and v15) or `type` (v13), and can have as values `in_invoice`, `in_refund`, `in_receipt`, `out_invoice`, `out_refund`, `out_receipt` or `entry`.

**Comment by driehuis** [comment]
I didn't spot this issue when I went over the issue list, but pull request #911 adresses this issue when it comes to the PDF report. @TeoGoddet, what was your concern when you asked your original question?
