### ISSUE TITLE
[Question] B2B and Core Mandates in the same debit order

### ISSUE THREAD

**Issue by rp-landoo** [OCA/bank-payment#857]
Hello!

I have a question, does anybody try to do a debit orden mixing payment lines with B2B and Core mandate format?

I did it, but it went wrong because the whole debit order was uploaded to the bank as B2B. Is this the expected result?

Thanks!

**Comment by rp-landoo** [comment]
Hello!

In V13 I tried to upload a debit order to a Spanish mixing payment lineas with B2B and Core mandates, but something went wrong. The whole debit order was uploaded as B2B to the bank. @CarlosRoca13 would you know why this is happening? Is the module prepared to mix B2B and Core in the same debit order?

Thanks!

**Comment by pedrobaeza** [comment]
SEPA doesn't allow to mix both. It's not something of the modules.

**Comment by rp-landoo** [comment]
Thank you very much.

Is there any filter that allows me not to mix them. If I want to import all payment lines from one specific due date, I am no able to select if they have B2b or Core mandate.

Thanks again!

**Comment by pedrobaeza** [comment]
No.
