### ISSUE TITLE
account.invoice error when installing V14 account_payment_mode

### ISSUE THREAD

**Issue by ashleybarto** [OCA/bank-payment#862]
getting Model 'account.invoice' does not exist in registry error when installing v14 of account_payment_mode.  This should be replaced in V13.

**Comment by pedrobaeza** [comment]
You are not installing the proper version of the module. You can try in OCA runbot that is working.

**Comment by ashleybarto** [comment]
I am running V14 of Odoo and v14 of the module according to module info in Odoo.   Is there something else check.  account is the only dependency and it is installed.

**Comment by pedrobaeza** [comment]
Check that you have this code: https://github.com/OCA/bank-payment/tree/14.0/account_payment_mode

**Comment by ashleybarto** [comment]
yes, that is the code source. V14 for sure.

**Comment by pedrobaeza** [comment]
Search on your code where is the source of account.invoice, as it's not this code.

**Comment by ashleybarto** [comment]
I did a text search in the account_payment_mode and did not find it either.  I am not sure of the source of that error. I am not installing any other module, just that one.

**Comment by pedrobaeza** [comment]
You should have other module involved with such old code.

**Comment by ashleybarto** [comment]
I did an update apps again as I had done before and this time it installed. Thanks.
