### ISSUE TITLE
account_payment_partner V14 parse installation error

### ISSUE THREAD

**Issue by ashleybarto** [OCA/bank-payment#863]
Anyone know what is causing this on installation?  Source is bank-payment-14.0. Thanks.
[Odoo parse error.pdf](https://github.com/OCA/bank-payment/files/7412046/Odoo.parse.error.pdf)

**Comment by bodedra** [comment]
@ashleybarto It's an issue in your deployment. "account_payment_partner" module depends on "account_payment_mode". Make sure you have that module.

We can close this issue.
