### ISSUE TITLE
Error registering payment - account.move(<NewId 0x7fc3c45842e8>,).payment_mode_id

### ISSUE THREAD

**Issue by japm23** [OCA/bank-payment#865]
Hi, sorry for my English.
I have Odoo 13 and for a few days I skip this error to register payments

## Module
Account Payment Mode - Ver. 13.0.1.0.0

## Describe the bug
When registering the payment of an invoice I skip this error:
account.move(<NewId 0x7fc3c45842e8>,).payment_mode_id

1. Order sale
2. Picking
3. Invoice
4. register payment
5. Select bank
6.  And error

Any ideas?
I have uninstalled the module and reinstalled it, I have deleted the payment methods and I have recreated them exactly the same.
I have tried with another bank, with the cash box, another invoice, another customer and in all of them I get this error.

Thanks!!!

**Comment by pedrobaeza** [comment]
Are you able to reproduce it on OCA runbot?

**Comment by japm23** [comment]
No, sorry,I don't like how to do it

**Comment by pedrobaeza** [comment]
Click on the badge in the README.
