### ISSUE TITLE
account_banking incompatible with cash management

### ISSUE THREAD

**Issue by NL66278** [OCA/bank-payment#88]
Installing account_banking leads to errors when using Cash Management.

After installing account_banking, when clicking on a Cash register, the following error-window appears:
OpenERP Client Error

Error: Unknown field state in domain [["state","not in",["draft"]]]

http://localhost:10021/web/static/src/js/view_form.js:1688

I think this is due to added fields to account_bank_stament_line that have readonly conditioned on state directly added to model, instead of in in view.

It is a very unfortunate datamodel design to have cash transactions and bank transactions in the same table/model. However I will try to fix the error.

**Comment by StefanRijnhart** [comment]
For the record, patch in #89

**Comment by pedrobaeza** [comment]
Patch is merged, so I close.
