### ISSUE TITLE
Hello dear team. I am new to odoo. Currently working on odoo 12. I am getting this error since yesterday "Could not get content for /account_parent/static/src/scss/coa_hierarchy.scss defined in bundle 'web.assets_common'." Please I need your assistance

### ISSUE THREAD

**Issue by soyames** [OCA/bank-payment#892]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
This has nothing to do with this repo.

**Comment by soyames** [comment]
> 

I really don't know how to solve the issue
