### ISSUE TITLE
[14.0] account_payment_purchase: changing many2one resets payment_mode

### ISSUE THREAD

**Issue by ae-landoo** [OCA/bank-payment#899]
Hi,
We've seen that when the field purchase_vendor_bill_id is changed and a purchase is selected from it, the payment_mode_id is always reseted because it is using the reference purchase_id.
`new_mode = self.purchase_id.payment_mode_id.id or False`
We've made this change, and it seems to work as it should.
`new_mode = self.purchase_vendor_bill_id.purchase_order_id.payment_mode_id.id or False`
The same goes for the partner_bank_id field.
@MiquelRForgeFlow

**Comment by Mat-moran** [comment]
We have test your solution and it works OK. We are going to propose PR, if you prefer to do it yourself just remove ours.
Thanks @ae-landoo

**Comment by ae-landoo** [comment]
Just do it by yourself, it is ok for us.
Best regards @Mat-moran
