### ISSUE TITLE
Use several transfer account on same journal on v14

### ISSUE THREAD

**Issue by angelmoya** [OCA/bank-payment#902]
## Module
account_payment_order

I have a bank journal, in wich I use two payment type, and I want to use tiwce outstanding payments account. For example for long term financing and sort term financing.

On previous versions I can create two payment mode, and set diferent transfer account on it, but in versión 14 I can only put one account on journal.

Any way to fix it?

**Comment by pedrobaeza** [comment]
Create another journal with the same bank account linked. I have yet to check how reconciliation goes with this though.

**Comment by angelmoya** [comment]
Thanks Pedro, I'm doing this way... but also is not 100% god for me.

This way I need to create another journal with another account for bank ... not only the transfer account.

For example:

- journal for Bank Account:
  - account for bank (real)
- journal for payment type, must be bank type
  -  account for bank (fake, because I can not use the same)
  - transfer account here (OK)
-  journal for other payment type, must be bank type 
  -  account for bank (fake, because I can not use the same)
  - transfer account here (OK)
