### ISSUE TITLE
[FIX] account_payment_order

### ISSUE THREAD

**Issue by tbanevicius** [OCA/bank-payment#950]
Issue in module --> Account Payment Order

Bank journal in the payment order is not populated correctly.

Affected versions: 15.0.1.0.0

Create payment mode, set Link to Bank Account to Fixed and select any journal.
Start creating new payment order and select above created payment mode.
Bank Journal is not filled in, nor it should be applied from the payment mode.
Bank journal should be populated whenever payment mode is changed.

**Comment by rafaelbn** [comment]
I confirm this issue it's not populated.

@tbanevicius 😄 recommendations:

A good subject get more readers like

[FIX][account_payment_order] Bank Journal don't populate in payment order

**Comment by pedrobaeza** [comment]
Handled in #951, so closing

**Comment by aisopuro** [comment]
@pedrobaeza heads up, #951 was auto-closed by bot without merging, so this issue isn't actually fixed as far as I'm aware.

**Comment by pedrobaeza** [comment]
Well, the PR was not answered, so the one that needs to be reborn is the PR, not the issue.
