### ISSUE TITLE
account_payment_partner blocks selection of move lines not linked to an invoice

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#98]
Here is the scenario to reproduce the bug on v8:

1) Create a new DB with demo data
2) Install the module account_banking_sepa_credit_transfer
3) In Accounting > Journal entries, create a new account.move in the purchase journal:
1st line:
Name : expense not linked to an invoice
Partner : vauxoo
Account : any expense account
debit : 42
2nd line:
Name : same as 1st line
Partner : same as 1st line
Account : third party supplier account (401100 in France)
credit : 42

4) Create a new payment order with payment mode "SEPA credit transfer la banque postale"

5) Click on the "Invoice" button to start the wizard. Uncheck the option "Populate results
 directly". Then click on "Search", then "Add an item" : it will give you access to the account.move.line of 42€ of vauxoo, which is not linked to an invoice => Good.
Cancel the addition of the account move line.

6) Install the module account_payment_partner

7) Go back to the payment order you created at step 4 (it should not have any payment line, as you cancelled the addition of the move line). Click on the "Invoice" button to start the wizard. Uncheck the option "Populate results directly". Then click on "Search", then "Add an item" : you DON'T have access to the account.move.line of 42€ of Vauxoo. That's a bug.

Code analysis:
This bug is caused by the code in account_payment_partner/wizard/payment_order_create.py line 33: this update of the domain is "designed" to accept the move lines with invoice = False, but in fact it blocks the account.move.lines that have invoice = False.

For the moment, I haven't found a way to update the domain without blocking the account.move.line with invoice = False. The only solution I see for the moment is to have a field "payment_mode_id" on the account.move.line (it's value would be copied from the invoice to the account.move.line) and filter like that:

```
domain += ['|', ('payment_mode_id', '=', False), ('payment_mode_id', '=', payment_order.mode.id)]
```

I hope we can find a better solution, because the solution above requires an update of the datamodel, which is a pain.

**Comment by sbidoul** [comment]
@alexis-via Your domain in account_payment_partner/wizard/payment_order_create.py line 33 looks fine to me.

Since account_move_line.invoice is a function field with a search function I'd bet the bug is in that search function.

If you do an advanced search on move line with Invoice is not set, you get no result and the following query is executed `SELECT l.id FROM account_move_line l, account_invoice i WHERE l.move_id = i.move_id  AND(i.id IS NULL)` which at first glance is not correct.

**Comment by alexis-via** [comment]
@sbidoul Thanks for your idea. I'll try to search in the direction you suggest (as soon as I have time...)

**Comment by alexis-via** [comment]
@sbidoul I confirm your analysis. I reported the bug on odoo https://github.com/odoo/odoo/issues/4857

**Comment by sbidoul** [comment]
This bug has been worked around by #139. The upstream bug remains, though.
