### ISSUE TITLE
Generated move lines are being grouped by FRST/RCUR instead of by RECURRENT/ONEOFF

### ISSUE THREAD

**Issue by joao-jeronimo** [OCA/bank-payment#987]
## Module
account_banking_sepa_direct_debit

## Describe the bug
Generated account moves lines are being grouped by order type instead of by mandate type.

## To Reproduce
**Affected versions**: all

1. Generate a SEPA xml file, where some mandates have a FRST sequence and others have a RCUR sequence.
2. Mark the payment order as submitted.
3. As a resulta, 2 account.moves are generated.
4. Cancel the payment order and fully validate it again.
5. As now every mandate is RCUR, only one account.move is generated.

**Expected behavior**
Generating the same quantity of account.move's every time the payment order is marked as file-submited, unless the mandate is of a different type.

**The fix**
To fix this, edit the bank-payment/account_banking_sepa_direct_debit/models/bank_payment_line.py file and where it says:
hashcode += "-" + str(self.mandate_id.recurrent_sequence_type)
Replace by:
hashcode += "-" + str(self.mandate_id.type)

**Comment by pedrobaeza** [comment]
Please check #979 where the rules change and this may not be a problem.
